/**
  * SiebelCreateOrderIn.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.siebel.xmlmapper.maps;

import com.haht.xml.*;
import com.haht.xml.transform.*;
import com.haht.xml.library.*;
import com.custom.siebel.xmlmapper.*;

public class SiebelCreateOrderIn extends com.custom.yantra.xmlmapper.YantraMapper
{	
    protected static final int QUAL_NONE = 0;
    protected static final int QUAL_STAR = 1;
    protected static final int QUAL_PLUS = 2;
    protected static final int QUAL_HOOK = 3;

    protected static final int TYPE_ELEM = 0;
    protected static final int TYPE_ALT = 1;
    protected static final int TYPE_SEQ = 2;
    protected static final int TYPE_MIXED = 3;
    protected static final int TYPE_TEXT = 4;
    protected static final int TYPE_EMPTY = 5;
    protected static final int TYPE_ANY = 6;


    /////////////////////////////////////////////////////////////////////////
    // Target Content Model
    /////////////////////////////////////////////////////////////////////////

	protected static final int ID_ORDER = 0;
	protected static final int ID_YFC_DOC = 1;
	protected static final int ID_ORDERLINES = 2;
	protected static final int ID_PRODUCTSERVICEASSOCS = 3;
	protected static final int ID_NOTES = 4;
	protected static final int ID_INSTRUCTIONS = 5;
	protected static final int ID_PERSONINFOSHIPTO = 6;
	protected static final int ID_PERSONINFOBILLTO = 7;
	protected static final int ID_PERSONINFOMARKFOR = 8;
	protected static final int ID_PERSONINFOCONTACT = 9;
	protected static final int ID_ADDITIONALADDRESSES = 10;
	protected static final int ID_PRICEINFO = 11;
	protected static final int ID_HEADERCHARGES = 12;
	protected static final int ID_HEADERTAXES = 13;
	protected static final int ID_REFERENCES = 14;
	protected static final int ID_PAYMENTMETHODS = 15;
	protected static final int ID_ORDERDATES = 16;
	protected static final int ID_SPECIALSERVICES = 17;
	protected static final int ID_ORDERHOLDTYPES = 18;
	protected static final int ID_ORDERLINE = 19;
	protected static final int ID_PRODUCTSERVICEASSOC = 20;
	protected static final int ID_NOTE = 21;
	protected static final int ID_INSTRUCTION = 22;
	protected static final int ID_ADDITIONALADDRESS = 23;
	protected static final int ID_HEADERCHARGE = 24;
	protected static final int ID_HEADERTAX = 25;
	protected static final int ID_REFERENCE = 26;
	protected static final int ID_PAYMENTMETHOD = 27;
	protected static final int ID_ORDERDATE = 28;
	protected static final int ID_SPECIALSERVICE = 29;
	protected static final int ID_ORDERHOLDTYPE = 30;
	protected static final int ID_ORDERLINETRANQUANTITY = 31;
	protected static final int ID_DERIVEDFROM = 32;
	protected static final int ID_ORDERLINEOPTIONS = 33;
	protected static final int ID_ITEM = 34;
	protected static final int ID_LINEPRICEINFO = 35;
	protected static final int ID_LINECHARGES = 36;
	protected static final int ID_LINETAXES = 37;
	protected static final int ID_KITLINES = 38;
	protected static final int ID_SCHEDULES = 39;
	protected static final int ID_DEPENDENCY = 40;
	protected static final int ID_ORDERLINEINVATTREQUEST = 41;
	protected static final int ID_PRODUCTITEMS = 42;
	protected static final int ID_BUNDLEPARENTLINE = 43;
	protected static final int ID_PRODUCTLINE = 44;
	protected static final int ID_SERVICELINE = 45;
	protected static final int ID_PERSONINFO = 46;
	protected static final int ID_PAYMENTDETAILS = 47;
	protected static final int ID_ORDERLINEOPTION = 48;
	protected static final int ID_LINECHARGE = 49;
	protected static final int ID_LINETAX = 50;
	protected static final int ID_KITLINE = 51;
	protected static final int ID_SCHEDULE = 52;
	protected static final int ID_PRODUCTITEM = 53;
	protected static final int ID_KITLINETRANQUANTITY = 54;
	protected static final int ID_SCHEDULETRANQUANTITY = 55;


    protected static com.haht.xml.wrapper.ContentModel[] rTargetModels =
    {
		new com.haht.xml.wrapper.ContentModel("Order", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("yfc:doc", null,  TYPE_TEXT, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLines", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductServiceAssocs", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Notes", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Instructions", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoShipTo", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoBillTo", null,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoMarkFor", null,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoContact", null,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AdditionalAddresses", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PriceInfo", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderCharges", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderTaxes", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("References", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PaymentMethods", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderDates", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("SpecialServices", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderHoldTypes", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLine", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductServiceAssoc", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Note", null,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Instruction", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AdditionalAddress", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderCharge", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderTax", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Reference", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PaymentMethod", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderDate", null,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("SpecialService", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderHoldType", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineTranQuantity", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("DerivedFrom", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineOptions", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Item", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LinePriceInfo", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineCharges", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineTaxes", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLines", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Schedules", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Dependency", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineInvAttRequest", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductItems", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("BundleParentLine", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductLine", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ServiceLine", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfo", null,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PaymentDetails", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineOption", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineCharge", null,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineTax", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLine", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Schedule", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductItem", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLineTranQuantity", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ScheduleTranQuantity", null,  TYPE_SEQ, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rTargetModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTSERVICEASSOCS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_NOTES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOSHIPTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOBILLTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOMARKFOR, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOCONTACT, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRICEINFO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_HEADERCHARGES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_HEADERTAXES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REFERENCES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PAYMENTMETHODS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERDATES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SPECIALSERVICES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERHOLDTYPES, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERLINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PRODUCTSERVICEASSOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_NOTE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ null },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESS, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_HEADERCHARGE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_HEADERTAX, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_REFERENCE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PAYMENTMETHOD, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERDATE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SPECIALSERVICE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERHOLDTYPE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINETRANQUANTITY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_DERIVEDFROM, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINEOPTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ITEM, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOSHIPTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOMARKFOR, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEPRICEINFO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINECHARGES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINETAXES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REFERENCES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_KITLINES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SCHEDULES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_DEPENDENCY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERDATES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINEINVATTREQUEST, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTITEMS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_BUNDLEPARENTLINE, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTLINE, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SERVICELINE, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFO, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PAYMENTDETAILS, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERLINEOPTION, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_LINECHARGE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_LINETAX, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_KITLINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SCHEDULE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PRODUCTITEM, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_KITLINETRANQUANTITY, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SCHEDULETRANQUANTITY, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },

    };

    protected com.haht.xml.wrapper.ContentModel getTargetModel(int id)
    {
		return rTargetModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getTargetModelItems(int id)
    {
		return rTargetModelItems[id];
    }

    /////////////////////////////////////////////////////////////////////////
    // Transformation map
    /////////////////////////////////////////////////////////////////////////

    private static Object[][] rProcess =
    {
		{ new ExpressionProcess(SiebelCreateOrderIn.class, "_expression_0_0", "", "") },
		{ new ExpressionProcess(SiebelCreateOrderIn.class, "_expression_1_0", "", "") },
		{ null },
		{ null },
		{ new ExpressionProcess(SiebelCreateOrderIn.class, "_expression_4_0", "", "") },
		{ null },
		{ new ExpressionProcess(SiebelCreateOrderIn.class, "_expression_6_0", "", "") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_7_0", "java.lang.String", "org.w3c.dom.Node"), new FilterProcess(SiebelCreateOrderIn.class, "_filter_7_1", "java.lang.String", "org.w3c.dom.Node") },
		{ null },
		{ null },
		{ null },
		{ null },
		{ new ExpressionProcess(SiebelCreateOrderIn.class, "_expression_12_0", "", "") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_13_0", "java.lang.String", "org.w3c.dom.Node") },
		{ null },
		{ new FilterProcess(SiebelCreateOrderIn.class, "_filter_15_0", "java.lang.String", "org.w3c.dom.Node") },
		{ null },
		{ null },
		{ null },
		{ null },
		{ null },
		{ null },
		{ null },
		{ new ExpressionProcess(SiebelCreateOrderIn.class, "_expression_23_0", "", "") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_24_0", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_25_0", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_26_0", "java.lang.String", "org.w3c.dom.Node"), new FilterProcess(SiebelCreateOrderIn.class, "_filter_26_1", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_27_0", "java.lang.String", "org.w3c.dom.Node"), new FilterProcess(SiebelCreateOrderIn.class, "_filter_27_1", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_28_0", "java.lang.String", "org.w3c.dom.Node"), new FilterProcess(SiebelCreateOrderIn.class, "_filter_28_1", "java.lang.String", "org.w3c.dom.Node") },
		{ new ExpressionProcess(SiebelCreateOrderIn.class, "_expression_29_0", "", "") },
		{ null },
		{ null },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_32_0", "java.lang.String", "org.w3c.dom.Node"), new FilterProcess(SiebelCreateOrderIn.class, "_filter_32_1", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_33_0", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_34_0", "java.lang.String", "org.w3c.dom.Node"), new FilterProcess(SiebelCreateOrderIn.class, "_filter_34_1", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_35_0", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_36_0", "java.lang.String", "org.w3c.dom.Node"), new FilterProcess(SiebelCreateOrderIn.class, "_filter_36_1", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_37_0", "java.lang.String", "org.w3c.dom.Node") },
		{ null },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_39_0", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_40_0", "java.lang.String", "org.w3c.dom.Node"), new FilterProcess(SiebelCreateOrderIn.class, "_filter_40_1", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_41_0", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_42_0", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_43_0", "java.lang.String", "org.w3c.dom.Node"), new FilterProcess(SiebelCreateOrderIn.class, "_filter_43_1", "java.lang.String", "org.w3c.dom.Node") },
		{ null },
		{ null },
		{ null },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_47_0", "java.lang.String", "org.w3c.dom.Node") },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_48_0", "java.lang.String", "org.w3c.dom.Node") },
		{ null },
		{ null },
		{ null },
		{ new ConditionProcess(SiebelCreateOrderIn.class, "_condition_52_0", "java.lang.String", "org.w3c.dom.Node") },
		{ null },

    };

    private static MapEntry[] rMapEntries =
    {
		new MapEntry(
				0,
				0,
				-1,
				"",
				"",
				"Order",
				"BuyerOrganizationCode",
				"",
				rProcess[0]),

		new MapEntry(
				1,
				0,
				-1,
				"",
				"",
				"Order",
				"SellerOrganizationCode",
				"",
				rProcess[1]),

		new MapEntry(
				2,
				0,
				-1,
				"ListOfOrderInterface/Orders/OrderType",
				"",
				"",
				"",
				"1:1:1",
				rProcess[2]),

		new MapEntry(
				3,
				0,
				-1,
				"ListOfOrderInterface/Orders/OrderTypeId",
				"",
				"",
				"",
				"1:1:1",
				rProcess[3]),

		new MapEntry(
				4,
				0,
				-1,
				"",
				"",
				"Order",
				"OrderType",
				"",
				rProcess[4]),

		new MapEntry(
				5,
				0,
				-1,
				"ListOfOrderInterface/Orders/PrimaryOrganization",
				"",
				"",
				"",
				"1:1:1",
				rProcess[5]),

		new MapEntry(
				6,
				0,
				-1,
				"",
				"",
				"Order",
				"EnterpriseCode",
				"",
				rProcess[6]),

		new MapEntry(
				7,
				0,
				-1,
				"ListOfOrderInterface/Orders/RequestedDate",
				"",
				"Order",
				"ReqDeliveryDate",
				"1:1:1",
				rProcess[7]),

		new MapEntry(
				8,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/Id",
				"",
				"",
				"",
				"1:1:1:n:1",
				rProcess[8]),

		new MapEntry(
				9,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/ProductId",
				"",
				"",
				"",
				"1:1:1:n:1",
				rProcess[9]),

		new MapEntry(
				10,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/PartNumber",
				"",
				"",
				"",
				"1:1:1:n:1",
				rProcess[10]),

		new MapEntry(
				11,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/IntegrationId",
				"",
				"",
				"",
				"1:1:1:n:1",
				rProcess[11]),

		new MapEntry(
				12,
				0,
				-1,
				"",
				"",
				"Order/OrderLines/OrderLine/Item",
				"ItemID",
				"",
				rProcess[12]),

		new MapEntry(
				13,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/Note",
				"",
				"Order/Notes/Note",
				"NoteText",
				"1:1:1:n:1",
				rProcess[13]),

		new MapEntry(
				14,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/RequestedQuantity",
				"",
				"Order/OrderLines/OrderLine",
				"OrderedQty",
				"1:1:1:n:1",
				rProcess[14]),

		new MapEntry(
				15,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/UnitofMeasure",
				"",
				"Order/OrderLines/OrderLine/Item",
				"UnitOfMeasure",
				"1:1:1:n:1",
				rProcess[15]),

		new MapEntry(
				16,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems",
				"",
				"Order/OrderLines/OrderLine",
				"",
				"1:1:1:n",
				rProcess[16]),

		new MapEntry(
				17,
				0,
				-1,
				"ListOfOrderInterface/Orders/BillToAccount",
				"",
				"",
				"",
				"1:1:1",
				rProcess[17]),

		new MapEntry(
				18,
				0,
				-1,
				"ListOfOrderInterface/Orders/BillToAccountId",
				"",
				"",
				"",
				"1:1:1",
				rProcess[18]),

		new MapEntry(
				19,
				0,
				-1,
				"ListOfOrderInterface/Orders/BillToAccountIntegrationId",
				"",
				"",
				"",
				"1:1:1",
				rProcess[19]),

		new MapEntry(
				20,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/ProductIntegrationId",
				"",
				"",
				"",
				"1:1:1:n:1",
				rProcess[20]),

		new MapEntry(
				21,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfRelatedSalesRep/RelatedSalesRep/Login",
				"",
				"",
				"",
				"1:1:1:n:1",
				rProcess[21]),

		new MapEntry(
				22,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfRelatedSalesRep/RelatedSalesRep/Position",
				"",
				"",
				"",
				"1:1:1:n:1",
				rProcess[22]),

		new MapEntry(
				23,
				0,
				-1,
				"",
				"",
				"Order",
				"EnteredBy",
				"",
				rProcess[23]),

		new MapEntry(
				24,
				0,
				-1,
				"ListOfOrderInterface/Orders/DiscountAmount",
				"",
				"Order/HeaderCharges/HeaderCharge",
				"ChargeAmount",
				"1:1:1",
				rProcess[24]),

		new MapEntry(
				25,
				0,
				-1,
				"ListOfOrderInterface/Orders/TaxAmount",
				"",
				"Order/HeaderTaxes/HeaderTax",
				"Tax",
				"1:1:1",
				rProcess[25]),

		new MapEntry(
				26,
				0,
				-1,
				"ListOfOrderInterface/Orders/DiscountAmount",
				"",
				"Order/HeaderCharges/HeaderCharge",
				"ChargeCategory",
				"1:1:1",
				rProcess[26]),

		new MapEntry(
				27,
				0,
				-1,
				"ListOfOrderInterface/Orders/TaxAmount",
				"",
				"Order/HeaderTaxes/HeaderTax",
				"TaxName",
				"1:1:1",
				rProcess[27]),

		new MapEntry(
				28,
				0,
				-1,
				"ListOfOrderInterface/Orders/SubmitDate",
				"",
				"Order",
				"OrderDate",
				"1:1:1",
				rProcess[28]),

		new MapEntry(
				29,
				0,
				-1,
				"",
				"",
				"Order",
				"DraftOrderFlag",
				"",
				rProcess[29]),

		new MapEntry(
				30,
				0,
				-1,
				"ListOfOrderInterface/Orders/CurrencyCode",
				"",
				"Order/PriceInfo",
				"Currency",
				"1:1:1",
				rProcess[30]),

		new MapEntry(
				31,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/LineNumber",
				"",
				"Order/OrderLines/OrderLine",
				"PrimeLineNo",
				"1:1:1:n:1",
				rProcess[31]),

		new MapEntry(
				32,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/RequestedDate",
				"",
				"Order/OrderLines/OrderLine",
				"ReqDeliveryDate",
				"1:1:1:n:1",
				rProcess[32]),

		new MapEntry(
				33,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/DiscountAmount",
				"",
				"Order/OrderLines/OrderLine/LineCharges/LineCharge",
				"ChargePerUnit",
				"1:1:1:n:1",
				rProcess[33]),

		new MapEntry(
				34,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/DiscountAmount",
				"",
				"Order/OrderLines/OrderLine/LineCharges/LineCharge",
				"ChargeCategory",
				"1:1:1:n:1",
				rProcess[34]),

		new MapEntry(
				35,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/TaxAmount",
				"",
				"Order/OrderLines/OrderLine/LineTaxes/LineTax",
				"Tax",
				"1:1:1:n:1",
				rProcess[35]),

		new MapEntry(
				36,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/TaxAmount",
				"",
				"Order/OrderLines/OrderLine/LineTaxes/LineTax",
				"TaxName",
				"1:1:1:n:1",
				rProcess[36]),

		new MapEntry(
				37,
				0,
				-1,
				"ListOfOrderInterface/Orders/ShipComplete",
				"",
				"Order",
				"ShipCompleteFlag",
				"1:1:1",
				rProcess[37]),

		new MapEntry(
				38,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/HoldFlag",
				"",
				"Order/OrderLines/OrderLine",
				"HoldFlag",
				"1:1:1:n:1",
				rProcess[38]),

		new MapEntry(
				39,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/StartPrice",
				"",
				"Order/OrderLines/OrderLine/LinePriceInfo",
				"UnitPrice",
				"1:1:1:n:1",
				rProcess[39]),

		new MapEntry(
				40,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/ShippingCharges",
				"",
				"Order/OrderLines/OrderLine/LineCharges/LineCharge",
				"ChargeCategory",
				"1:1:1:n:1",
				rProcess[40]),

		new MapEntry(
				41,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/ShippingCharges",
				"",
				"Order/OrderLines/OrderLine/LineCharges/LineCharge",
				"ChargePerUnit",
				"1:1:1:n:1",
				rProcess[41]),

		new MapEntry(
				42,
				0,
				-1,
				"ListOfOrderInterface/Orders/ShippingCharges",
				"",
				"Order/HeaderCharges/HeaderCharge",
				"ChargeAmount",
				"1:1:1",
				rProcess[42]),

		new MapEntry(
				43,
				0,
				-1,
				"ListOfOrderInterface/Orders/ShippingCharges",
				"",
				"Order/HeaderCharges/HeaderCharge",
				"ChargeCategory",
				"1:1:1",
				rProcess[43]),

		new MapEntry(
				44,
				0,
				-1,
				"ListOfOrderInterface/Orders/Carrier",
				"",
				"Order",
				"SCAC",
				"1:1:1",
				rProcess[44]),

		new MapEntry(
				45,
				0,
				-1,
				"ListOfOrderInterface/Orders/CarrierPriority",
				"",
				"Order",
				"CarrierServiceCode",
				"1:1:1",
				rProcess[45]),

		new MapEntry(
				46,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/Id",
				"",
				"Order/OrderLines/OrderLine",
				"CustomerLinePONo",
				"1:1:1:n:1",
				rProcess[46]),

		new MapEntry(
				47,
				0,
				-1,
				"ListOfOrderInterface/Orders/PurchaseOrderNumber",
				"",
				"Order/PaymentMethods/PaymentMethod",
				"CustomerPONo",
				"1:1:1",
				rProcess[47]),

		new MapEntry(
				48,
				0,
				-1,
				"ListOfOrderInterface/Orders/PurchaseOrderNumber",
				"",
				"Order",
				"CustomerPONo",
				"1:1:1",
				rProcess[48]),

		new MapEntry(
				49,
				0,
				-1,
				"ListOfOrderInterface/Orders/PrimaryOrganizationId",
				"",
				"",
				"",
				"1:1:1",
				rProcess[49]),

		new MapEntry(
				50,
				0,
				-1,
				"ListOfOrderInterface/Orders/Id",
				"",
				"Order",
				"CustomerPONo",
				"1:1:1",
				rProcess[50]),

		new MapEntry(
				51,
				0,
				-1,
				"ListOfOrderInterface/Orders/OrderNumber",
				"",
				"Order",
				"OrderNo",
				"1:1:1",
				rProcess[51]),

		new MapEntry(
				52,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/ParentOrderItemId",
				"",
				"Order/OrderLines/OrderLine/BundleParentLine",
				"TransactionalLineId",
				"1:1:1:n:1",
				rProcess[52]),

		new MapEntry(
				53,
				0,
				-1,
				"ListOfOrderInterface/Orders/ListOfLineItems/LineItems/Id",
				"",
				"Order/OrderLines/OrderLine",
				"TransactionalLineId",
				"1:1:1:n:1",
				rProcess[53]),

    };

	private static TargetProperties m_TargetProperties = new TargetProperties
	(
			null,
			null,
			false,
			false

	);

	protected Content[] rContents;

	protected TargetProperties getTargetProperties()
	{
		return m_TargetProperties;
	}

    protected int getMapEntryCount()
    {
		return rMapEntries.length;
    }

    protected MapEntry getMapEntryAt(int i)
    {
		return rMapEntries[i];
    }

	protected int getContentCount()
	{
		return rContents.length;
	}

    protected Content getContentAt(int id)
    {
		return rContents[id];
    }

    protected HahtDocument instantiateSourceDOM(int nDocNum) throws HahtXMLException
    {
		HahtDocument doc;

		switch (nDocNum)
		{
		case 0:
			doc = new XercesDoc(false);
			break;

		default:
			doc = new XercesDoc(false);
			break;
		}
		return doc;
    }

	protected int getInputDocumentCount()
	{
		return 1;
	}

    public SiebelCreateOrderIn()
    {
		rContents = new Content[54];
		rContents[0] = new ExpressionContent(this, getMapEntryAt(0));
		rContents[1] = new ExpressionContent(this, getMapEntryAt(1));
		rContents[2] = new Content(this, getMapEntryAt(2));
		rContents[3] = new Content(this, getMapEntryAt(3));
		rContents[4] = new ExpressionContent(this, getMapEntryAt(4));
		rContents[5] = new Content(this, getMapEntryAt(5));
		rContents[6] = new ExpressionContent(this, getMapEntryAt(6));
		rContents[7] = new ValueOfContent(this, getMapEntryAt(7));
		rContents[8] = new Content(this, getMapEntryAt(8));
		rContents[9] = new Content(this, getMapEntryAt(9));
		rContents[10] = new Content(this, getMapEntryAt(10));
		rContents[11] = new Content(this, getMapEntryAt(11));
		rContents[12] = new ExpressionContent(this, getMapEntryAt(12));
		rContents[13] = new ValueOfContent(this, getMapEntryAt(13));
		rContents[14] = new ValueOfContent(this, getMapEntryAt(14));
		rContents[15] = new ValueOfContent(this, getMapEntryAt(15));
		rContents[16] = new GroupingContent(this, getMapEntryAt(16), "grpLines");
		rContents[17] = new Content(this, getMapEntryAt(17));
		rContents[18] = new Content(this, getMapEntryAt(18));
		rContents[19] = new Content(this, getMapEntryAt(19));
		rContents[20] = new Content(this, getMapEntryAt(20));
		rContents[21] = new Content(this, getMapEntryAt(21));
		rContents[22] = new Content(this, getMapEntryAt(22));
		rContents[23] = new ExpressionContent(this, getMapEntryAt(23));
		rContents[24] = new ValueOfContent(this, getMapEntryAt(24));
		rContents[25] = new ValueOfContent(this, getMapEntryAt(25));
		rContents[26] = new ValueOfContent(this, getMapEntryAt(26));
		rContents[27] = new ValueOfContent(this, getMapEntryAt(27));
		rContents[28] = new ValueOfContent(this, getMapEntryAt(28));
		rContents[29] = new ExpressionContent(this, getMapEntryAt(29));
		rContents[30] = new ValueOfContent(this, getMapEntryAt(30));
		rContents[31] = new ValueOfContent(this, getMapEntryAt(31));
		rContents[32] = new ValueOfContent(this, getMapEntryAt(32));
		rContents[33] = new ValueOfContent(this, getMapEntryAt(33));
		rContents[34] = new ValueOfContent(this, getMapEntryAt(34));
		rContents[35] = new ValueOfContent(this, getMapEntryAt(35));
		rContents[36] = new ValueOfContent(this, getMapEntryAt(36));
		rContents[37] = new ValueOfContent(this, getMapEntryAt(37));
		rContents[38] = new ValueOfContent(this, getMapEntryAt(38));
		rContents[39] = new ValueOfContent(this, getMapEntryAt(39));
		rContents[40] = new ValueOfContent(this, getMapEntryAt(40));
		rContents[41] = new ValueOfContent(this, getMapEntryAt(41));
		rContents[42] = new ValueOfContent(this, getMapEntryAt(42));
		rContents[43] = new ValueOfContent(this, getMapEntryAt(43));
		rContents[44] = new ValueOfContent(this, getMapEntryAt(44));
		rContents[45] = new ValueOfContent(this, getMapEntryAt(45));
		rContents[46] = new ValueOfContent(this, getMapEntryAt(46));
		rContents[47] = new ValueOfContent(this, getMapEntryAt(47));
		rContents[48] = new ValueOfContent(this, getMapEntryAt(48));
		rContents[49] = new Content(this, getMapEntryAt(49));
		rContents[50] = new ValueOfContent(this, getMapEntryAt(50));
		rContents[51] = new ValueOfContent(this, getMapEntryAt(51));
		rContents[52] = new ValueOfContent(this, getMapEntryAt(52));
		rContents[53] = new ValueOfContent(this, getMapEntryAt(53));

    }

	/////////////////////////////////////////////////////////////////////////
	// Set the variables defined by variable map entries
	/////////////////////////////////////////////////////////////////////////

	public void setVariables()
	{
		strOrderType = getContentAt(2).getNextString();
		strOrderTypeId = getContentAt(3).getNextString();
		strPrimaryOrganization = getContentAt(5).getNextString();
		strId = getContentAt(8).getStringArray();
		strProductId = getContentAt(9).getStringArray();
		strPartNum = getContentAt(10).getStringArray();
		strIntegrationId = getContentAt(11).getStringArray();
		strBillToAccount = getContentAt(17).getNextString();
		strBillToAccountId = getContentAt(18).getNextString();
		strBillToAccountIntegrationId = getContentAt(19).getNextString();
		strProductIntegrationId = getContentAt(20).getStringArray();
		strLogin = getContentAt(21).getStringArray();
		strPosition = getContentAt(22).getStringArray();
		strPrimaryOrganizationId = getContentAt(49).getNextString();

	}

	/////////////////////////////////////////////////////////////////////////
	// Inner classes for submaps
	/////////////////////////////////////////////////////////////////////////



    /////////////////////////////////////////////////////////////////////////
    // Generated process methods.
    /////////////////////////////////////////////////////////////////////////

	public String _expression_0_0() throws Exception { return SiebelMapperUtils.computeBuyerOrganizationCode (strBillToAccountId, strBillToAccountIntegrationId); }
	public String _expression_1_0() throws Exception { return SiebelMapperUtils.computeSellerOrganizationCode (strPrimaryOrganization); }
	public String _expression_4_0() throws Exception { return SiebelMapperUtils.computeOrderType (strOrderType, strOrderTypeId, true); }
	public String _expression_6_0() throws Exception { return SiebelMapperUtils.getDefaultOrgCode(); }
	public Boolean _condition_7_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public String _filter_7_1(String s, org.w3c.dom.Node node) throws Exception { return Conversions.convertDateTime(s,"MM/dd/yyy hh:mm:ss","yyyy-MM-dd'T'hh:mm:ss'Z'"); }
	public String _expression_12_0() throws Exception { return SiebelMapperUtils.computeItemID (getGroupIndex("grpLines"), strId, strIntegrationId, strPartNum, strProductId, strProductIntegrationId); }
	public Boolean _condition_13_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public String _filter_15_0(String s, org.w3c.dom.Node node) throws Exception { return SiebelMapperUtils.computeUOM (s, true); }
	public String _expression_23_0() throws Exception { return new String(strLogin[0]+","+strPosition[0]); }
	public Boolean _condition_24_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public Boolean _condition_25_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public Boolean _condition_26_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public String _filter_26_1(String s, org.w3c.dom.Node node) throws Exception { return "Discount"; }
	public Boolean _condition_27_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public String _filter_27_1(String s, org.w3c.dom.Node node) throws Exception { return "Tax"; }
	public Boolean _condition_28_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public String _filter_28_1(String s, org.w3c.dom.Node node) throws Exception { return Conversions.convertDateTime(s,"MM/dd/yyyy hh:mm:ss","yyyy-MM-dd'T'hh:mm:ss'Z'"); }
	public String _expression_29_0() throws Exception { return "Y"; }
	public Boolean _condition_32_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public String _filter_32_1(String s, org.w3c.dom.Node node) throws Exception { return Conversions.convertDateTime(s,"MM/dd/yyyy hh:mm:ss","yyyy-MM-dd'T'hh:mm:ss'Z'"); }
	public Boolean _condition_33_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public Boolean _condition_34_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public String _filter_34_1(String s, org.w3c.dom.Node node) throws Exception { return "Discount"; }
	public Boolean _condition_35_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public Boolean _condition_36_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public String _filter_36_1(String s, org.w3c.dom.Node node) throws Exception { return "Tax"; }
	public Boolean _condition_37_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public Boolean _condition_39_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public Boolean _condition_40_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public String _filter_40_1(String s, org.w3c.dom.Node node) throws Exception { return "Shipping"; }
	public Boolean _condition_41_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public Boolean _condition_42_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public Boolean _condition_43_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public String _filter_43_1(String s, org.w3c.dom.Node node) throws Exception { return "Shipping"; }
	public Boolean _condition_47_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public Boolean _condition_48_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }
	public Boolean _condition_52_0(String s, org.w3c.dom.Node node) throws Exception { return new Boolean(!s.equals("")); }


	/////////////////////////////////////////////////////////////////////////
	// Generate member variables
	/////////////////////////////////////////////////////////////////////////

	protected String strOrderType;
	protected String strOrderTypeId;
	protected String strPrimaryOrganization;
	protected String[] strId;
	protected String[] strProductId;
	protected String[] strPartNum;
	protected String[] strIntegrationId;
	protected String strBillToAccount;
	protected String strBillToAccountId;
	protected String strBillToAccountIntegrationId;
	protected String[] strProductIntegrationId;
	protected String[] strLogin;
	protected String[] strPosition;
	protected String strPrimaryOrganizationId;

}

