/**
  * SiebelOrderStatusIn.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.siebel.xmlmapper.maps;

import com.haht.xml.*;
import com.haht.xml.transform.*;

public class SiebelOrderStatusIn extends com.custom.yantra.xmlmapper.YantraMapper
{	
    protected static final int QUAL_NONE = 0;
    protected static final int QUAL_STAR = 1;
    protected static final int QUAL_PLUS = 2;
    protected static final int QUAL_HOOK = 3;

    protected static final int TYPE_ELEM = 0;
    protected static final int TYPE_ALT = 1;
    protected static final int TYPE_SEQ = 2;
    protected static final int TYPE_MIXED = 3;
    protected static final int TYPE_TEXT = 4;
    protected static final int TYPE_EMPTY = 5;
    protected static final int TYPE_ANY = 6;


    /////////////////////////////////////////////////////////////////////////
    // Target Content Model
    /////////////////////////////////////////////////////////////////////////

	protected static final int ID_ORDER = 0;
	protected static final int ID_YFC_DOC = 1;


    protected static com.haht.xml.wrapper.ContentModel[] rTargetModels =
    {
		new com.haht.xml.wrapper.ContentModel("Order", null,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("yfc:doc", null,  TYPE_TEXT, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rTargetModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },

    };

    protected com.haht.xml.wrapper.ContentModel getTargetModel(int id)
    {
		return rTargetModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getTargetModelItems(int id)
    {
		return rTargetModelItems[id];
    }

    /////////////////////////////////////////////////////////////////////////
    // Transformation map
    /////////////////////////////////////////////////////////////////////////

    private static Object[][] rProcess =
    {
		{ null },
		{ null },

    };

    private static MapEntry[] rMapEntries =
    {
		new MapEntry(
				0,
				0,
				-1,
				"ListOfOrderInterface/Orders/IntegrationId",
				"",
				"Order",
				"OrderHeaderKey",
				"1:1:1",
				rProcess[0]),

		new MapEntry(
				1,
				0,
				-1,
				"ListOfOrderInterface/Orders/ExternalOrderNumber",
				"",
				"Order",
				"OrderNo",
				"1:1:1",
				rProcess[1]),

    };

	private static TargetProperties m_TargetProperties = new TargetProperties
	(
			null,
			null,
			false,
			false

	);

	protected Content[] rContents;

	protected TargetProperties getTargetProperties()
	{
		return m_TargetProperties;
	}

    protected int getMapEntryCount()
    {
		return rMapEntries.length;
    }

    protected MapEntry getMapEntryAt(int i)
    {
		return rMapEntries[i];
    }

	protected int getContentCount()
	{
		return rContents.length;
	}

    protected Content getContentAt(int id)
    {
		return rContents[id];
    }

    protected HahtDocument instantiateSourceDOM(int nDocNum) throws HahtXMLException
    {
		HahtDocument doc;

		switch (nDocNum)
		{
		case 0:
			doc = new XercesDoc(false);
			break;

		default:
			doc = new XercesDoc(false);
			break;
		}
		return doc;
    }

	protected int getInputDocumentCount()
	{
		return 1;
	}

    public SiebelOrderStatusIn()
    {
		rContents = new Content[2];
		rContents[0] = new ValueOfContent(this, getMapEntryAt(0));
		rContents[1] = new ValueOfContent(this, getMapEntryAt(1));

    }

	/////////////////////////////////////////////////////////////////////////
	// Set the variables defined by variable map entries
	/////////////////////////////////////////////////////////////////////////

	public void setVariables()
	{

	}

	/////////////////////////////////////////////////////////////////////////
	// Inner classes for submaps
	/////////////////////////////////////////////////////////////////////////



    /////////////////////////////////////////////////////////////////////////
    // Generated process methods.
    /////////////////////////////////////////////////////////////////////////



	/////////////////////////////////////////////////////////////////////////
	// Generate member variables
	/////////////////////////////////////////////////////////////////////////


}

