/**
  * YCMStyleGridInputDoc.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.yantra.xmlwrapper;

/////////////////////////////////////////////////////////////////////////////
// IMPORTS
/////////////////////////////////////////////////////////////////////////////
import java.io.*;
import com.haht.xml.*;

public class YCMStyleGridInputDoc extends com.haht.xml.wrapper.Doc
{
	protected static final int ID_STYLEGRID = 0;
	protected static final int ID_YFC_DOC = 1;


    protected static com.haht.xml.wrapper.ContentModel[] rModels =
    {
		new com.haht.xml.wrapper.ContentModel("StyleGrid", StyleGrid.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("yfc:doc", Yfc_doc.class,  TYPE_TEXT, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },

    };

    protected com.haht.xml.wrapper.ContentModel getContentModel(int id)
    {
		return rModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getModelItems(int id)
    {
		return rModelItems[id];
    }

    @SuppressWarnings("rawtypes")
	protected Class getDocumentClass()
    {
		return XercesDoc.class;
    }

    public YCMStyleGridInputDoc(String xml) throws Exception
    {
		super(xml);
		m_Root = (StyleGrid) getRoot(ID_STYLEGRID);
    }

    public YCMStyleGridInputDoc(InputStream xml) throws Exception
    {
		super(xml);
		m_Root = (StyleGrid) getRoot(ID_STYLEGRID);
    }

    public YCMStyleGridInputDoc(Reader xml) throws Exception
    {
    	super(xml);
    	m_Root = (StyleGrid) getRoot(ID_STYLEGRID);
    }

    public StyleGrid getStyleGrid() { return m_Root; }
    StyleGrid m_Root;


    /////////////////////////////////////////////////////////////////////////
    // Element Classes
    /////////////////////////////////////////////////////////////////////////

	public class StyleGrid extends com.haht.xml.wrapper.Element
	{
		public StyleGrid(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_STYLEGRID; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class Yfc_doc extends com.haht.xml.wrapper.PcdataElement
	{
		public Yfc_doc(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_YFC_DOC; }
	}


}
