/**
  * YCPCommonCodeListOutputDoc.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.yantra.xmlwrapper;

/////////////////////////////////////////////////////////////////////////////
// IMPORTS
/////////////////////////////////////////////////////////////////////////////
import java.io.*;
import java.util.*;
import com.haht.xml.*;

public class YCPCommonCodeListOutputDoc extends com.haht.xml.wrapper.Doc
{
	protected static final int ID_COMMONCODELIST = 0;
	protected static final int ID_COMMONCODE = 1;


    protected static com.haht.xml.wrapper.ContentModel[] rModels =
    {
		new com.haht.xml.wrapper.ContentModel("CommonCodeList", CommonCodeList.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("CommonCode", CommonCode.class,  TYPE_EMPTY, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_COMMONCODE, QUAL_STAR) },
		{ null },

    };

    protected com.haht.xml.wrapper.ContentModel getContentModel(int id)
    {
		return rModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getModelItems(int id)
    {
		return rModelItems[id];
    }

    @SuppressWarnings("rawtypes")
	protected Class getDocumentClass()
    {
		return XercesDoc.class;
    }

    public YCPCommonCodeListOutputDoc(String xml) throws Exception
    {
		super(xml);
		m_Root = (CommonCodeList) getRoot(ID_COMMONCODELIST);
    }

    public YCPCommonCodeListOutputDoc(InputStream xml) throws Exception
    {
		super(xml);
		m_Root = (CommonCodeList) getRoot(ID_COMMONCODELIST);
    }

    public YCPCommonCodeListOutputDoc(Reader xml) throws Exception
    {
    	super(xml);
    	m_Root = (CommonCodeList) getRoot(ID_COMMONCODELIST);
    }

    public CommonCodeList getCommonCodeList() { return m_Root; }
    CommonCodeList m_Root;


    /////////////////////////////////////////////////////////////////////////
    // Element Classes
    /////////////////////////////////////////////////////////////////////////

	public class CommonCodeList extends com.haht.xml.wrapper.Element
	{
		public CommonCodeList(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_COMMONCODELIST; }

		@SuppressWarnings("rawtypes")
		public Enumeration getCommonCodeList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class CommonCode extends com.haht.xml.wrapper.Element
	{
		public CommonCode(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_COMMONCODE; }
	}


}
