/**
  * YDMConfirmShipmentOnSuccessEventDoc.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.yantra.xmlwrapper;

/////////////////////////////////////////////////////////////////////////////
// IMPORTS
/////////////////////////////////////////////////////////////////////////////
import java.io.*;
import java.util.*;
import com.haht.xml.*;

public class YDMConfirmShipmentOnSuccessEventDoc extends com.haht.xml.wrapper.Doc
{
	protected static final int ID_SHIPMENT = 0;
	protected static final int ID_TOADDRESS = 1;
	protected static final int ID_FROMADDRESS = 2;
	protected static final int ID_CONTAINERS = 3;
	protected static final int ID_INSTRUCTIONS = 4;
	protected static final int ID_SHIPMENTLINES = 5;
	protected static final int ID_SHIPMENTCHARGES = 6;
	protected static final int ID_ADDITIONALDATES = 7;
	protected static final int ID_YFC_DOC = 8;
	protected static final int ID_CONTAINER = 9;
	protected static final int ID_INSTRUCTION = 10;
	protected static final int ID_SHIPMENTLINE = 11;
	protected static final int ID_SHIPMENTCHARGE = 12;
	protected static final int ID_ADDITIONALDATE = 13;
	protected static final int ID_CONTAINERDETAILS = 14;
	protected static final int ID_SHIPMENTLINEINVATTREQUEST = 15;
	protected static final int ID_SHIPMENTTAGSERIALS = 16;
	protected static final int ID_CONTAINERDETAIL = 17;
	protected static final int ID_SHIPMENTTAGSERIAL = 18;


    protected static com.haht.xml.wrapper.ContentModel[] rModels =
    {
		new com.haht.xml.wrapper.ContentModel("Shipment", Shipment.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ToAddress", ToAddress.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("FromAddress", FromAddress.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Containers", Containers.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Instructions", Instructions.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ShipmentLines", ShipmentLines.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ShipmentCharges", ShipmentCharges.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AdditionalDates", AdditionalDates.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("yfc:doc", Yfc_doc.class,  TYPE_TEXT, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Container", Container.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Instruction", Instruction.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ShipmentLine", ShipmentLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ShipmentCharge", ShipmentCharge.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AdditionalDate", AdditionalDate.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ContainerDetails", ContainerDetails.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ShipmentLineInvAttRequest", ShipmentLineInvAttRequest.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ShipmentTagSerials", ShipmentTagSerials.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ContainerDetail", ContainerDetail.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ShipmentTagSerial", ShipmentTagSerial.class,  TYPE_SEQ, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_TOADDRESS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_FROMADDRESS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_CONTAINERS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SHIPMENTLINES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SHIPMENTCHARGES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALDATES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_CONTAINER, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SHIPMENTLINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SHIPMENTCHARGE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALDATE, QUAL_STAR) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_CONTAINERDETAILS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SHIPMENTLINEINVATTREQUEST, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SHIPMENTTAGSERIALS, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_CONTAINERDETAIL, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SHIPMENTTAGSERIAL, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SHIPMENTTAGSERIALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SHIPMENTLINE, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },

    };

    protected com.haht.xml.wrapper.ContentModel getContentModel(int id)
    {
		return rModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getModelItems(int id)
    {
		return rModelItems[id];
    }

    protected Class<XercesDoc> getDocumentClass()
    {
		return XercesDoc.class;
    }

    public YDMConfirmShipmentOnSuccessEventDoc(String xml) throws Exception
    {
		super(xml);
		m_Root = (Shipment) getRoot(ID_SHIPMENT);
    }

    public YDMConfirmShipmentOnSuccessEventDoc(InputStream xml) throws Exception
    {
		super(xml);
		m_Root = (Shipment) getRoot(ID_SHIPMENT);
    }

    public YDMConfirmShipmentOnSuccessEventDoc(Reader xml) throws Exception
    {
    	super(xml);
    	m_Root = (Shipment) getRoot(ID_SHIPMENT);
    }

    public Shipment getShipment() { return m_Root; }
    Shipment m_Root;


    /////////////////////////////////////////////////////////////////////////
    // Element Classes
    /////////////////////////////////////////////////////////////////////////

	public class Shipment extends com.haht.xml.wrapper.Element
	{
		public Shipment(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SHIPMENT; }

		public ToAddress getToAddress() { return (ToAddress) getAtom(0, 0); }
		public FromAddress getFromAddress() { return (FromAddress) getAtom(0, 1); }
		public Containers getContainers() { return (Containers) getAtom(0, 2); }
		public Instructions getInstructions() { return (Instructions) getAtom(0, 3); }
		public ShipmentLines getShipmentLines() { return (ShipmentLines) getAtom(0, 4); }
		public ShipmentCharges getShipmentCharges() { return (ShipmentCharges) getAtom(0, 5); }
		public AdditionalDates getAdditionalDates() { return (AdditionalDates) getAtom(0, 6); }
		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 7); }
	}

	public class ToAddress extends com.haht.xml.wrapper.Element
	{
		public ToAddress(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_TOADDRESS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class FromAddress extends com.haht.xml.wrapper.Element
	{
		public FromAddress(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_FROMADDRESS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class Containers extends com.haht.xml.wrapper.Element
	{
		public Containers(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CONTAINERS; }

		public Enumeration<?> getContainerList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class Instructions extends com.haht.xml.wrapper.Element
	{
		public Instructions(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INSTRUCTIONS; }

		public Enumeration<?> getInstructionList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ShipmentLines extends com.haht.xml.wrapper.Element
	{
		public ShipmentLines(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SHIPMENTLINES; }

		public Enumeration<?> getShipmentLineList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ShipmentCharges extends com.haht.xml.wrapper.Element
	{
		public ShipmentCharges(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SHIPMENTCHARGES; }

		public Enumeration<?> getShipmentChargeList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class AdditionalDates extends com.haht.xml.wrapper.Element
	{
		public AdditionalDates(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ADDITIONALDATES; }

		public Enumeration<?> getAdditionalDateList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class Yfc_doc extends com.haht.xml.wrapper.PcdataElement
	{
		public Yfc_doc(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_YFC_DOC; }
	}

	public class Container extends com.haht.xml.wrapper.Element
	{
		public Container(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CONTAINER; }

		public ContainerDetails getContainerDetails() { return (ContainerDetails) getAtom(0, 0); }
		public Instructions getInstructions() { return (Instructions) getAtom(0, 1); }
		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 2); }
	}

	public class Instruction extends com.haht.xml.wrapper.Element
	{
		public Instruction(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INSTRUCTION; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ShipmentLine extends com.haht.xml.wrapper.Element
	{
		public ShipmentLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SHIPMENTLINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public ShipmentLineInvAttRequest getShipmentLineInvAttRequest() { return (ShipmentLineInvAttRequest) getAtom(0, 1); }
		public ShipmentTagSerials getShipmentTagSerials() { return (ShipmentTagSerials) getAtom(0, 2); }
	}

	public class ShipmentCharge extends com.haht.xml.wrapper.Element
	{
		public ShipmentCharge(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SHIPMENTCHARGE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class AdditionalDate extends com.haht.xml.wrapper.Element
	{
		public AdditionalDate(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ADDITIONALDATE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ContainerDetails extends com.haht.xml.wrapper.Element
	{
		public ContainerDetails(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CONTAINERDETAILS; }

		public Enumeration<?> getContainerDetailList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ShipmentLineInvAttRequest extends com.haht.xml.wrapper.Element
	{
		public ShipmentLineInvAttRequest(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SHIPMENTLINEINVATTREQUEST; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ShipmentTagSerials extends com.haht.xml.wrapper.Element
	{
		public ShipmentTagSerials(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SHIPMENTTAGSERIALS; }

		public Enumeration<?> getShipmentTagSerialList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ContainerDetail extends com.haht.xml.wrapper.Element
	{
		public ContainerDetail(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CONTAINERDETAIL; }

		public ShipmentTagSerials getShipmentTagSerials() { return (ShipmentTagSerials) getAtom(0, 0); }
		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 1); }
		public ShipmentLine getShipmentLine() { return (ShipmentLine) getAtom(0, 2); }
	}

	public class ShipmentTagSerial extends com.haht.xml.wrapper.Element
	{
		public ShipmentTagSerial(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SHIPMENTTAGSERIAL; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}


}
