/**
  * YFSCreateOrderInputDoc.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.yantra.xmlwrapper;

/////////////////////////////////////////////////////////////////////////////
// IMPORTS
/////////////////////////////////////////////////////////////////////////////
import java.io.*;
import java.util.*;
import com.haht.xml.*;

public class YFSCreateOrderInputDoc extends com.haht.xml.wrapper.Doc
{
	protected static final int ID_ORDER = 0;
	protected static final int ID_YFC_DOC = 1;
	protected static final int ID_ORDERLINES = 2;
	protected static final int ID_PRODUCTSERVICEASSOCS = 3;
	protected static final int ID_NOTES = 4;
	protected static final int ID_INSTRUCTIONS = 5;
	protected static final int ID_PERSONINFOSHIPTO = 6;
	protected static final int ID_PERSONINFOBILLTO = 7;
	protected static final int ID_PERSONINFOMARKFOR = 8;
	protected static final int ID_PERSONINFOCONTACT = 9;
	protected static final int ID_ADDITIONALADDRESSES = 10;
	protected static final int ID_PRICEINFO = 11;
	protected static final int ID_HEADERCHARGES = 12;
	protected static final int ID_HEADERTAXES = 13;
	protected static final int ID_REFERENCES = 14;
	protected static final int ID_PAYMENTMETHODS = 15;
	protected static final int ID_ORDERDATES = 16;
	protected static final int ID_SPECIALSERVICES = 17;
	protected static final int ID_ORDERHOLDTYPES = 18;
	protected static final int ID_ORDERLINE = 19;
	protected static final int ID_PRODUCTSERVICEASSOC = 20;
	protected static final int ID_NOTE = 21;
	protected static final int ID_INSTRUCTION = 22;
	protected static final int ID_ADDITIONALADDRESS = 23;
	protected static final int ID_HEADERCHARGE = 24;
	protected static final int ID_HEADERTAX = 25;
	protected static final int ID_REFERENCE = 26;
	protected static final int ID_PAYMENTMETHOD = 27;
	protected static final int ID_ORDERDATE = 28;
	protected static final int ID_SPECIALSERVICE = 29;
	protected static final int ID_ORDERHOLDTYPE = 30;
	protected static final int ID_ORDERLINETRANQUANTITY = 31;
	protected static final int ID_DERIVEDFROM = 32;
	protected static final int ID_ORDERLINEOPTIONS = 33;
	protected static final int ID_ITEM = 34;
	protected static final int ID_LINEPRICEINFO = 35;
	protected static final int ID_LINECHARGES = 36;
	protected static final int ID_LINETAXES = 37;
	protected static final int ID_KITLINES = 38;
	protected static final int ID_SCHEDULES = 39;
	protected static final int ID_DEPENDENCY = 40;
	protected static final int ID_ORDERLINEINVATTREQUEST = 41;
	protected static final int ID_PRODUCTITEMS = 42;
	protected static final int ID_BUNDLEPARENTLINE = 43;
	protected static final int ID_PRODUCTLINE = 44;
	protected static final int ID_SERVICELINE = 45;
	protected static final int ID_PERSONINFO = 46;
	protected static final int ID_PAYMENTDETAILS = 47;
	protected static final int ID_ORDERLINEOPTION = 48;
	protected static final int ID_LINECHARGE = 49;
	protected static final int ID_LINETAX = 50;
	protected static final int ID_KITLINE = 51;
	protected static final int ID_SCHEDULE = 52;
	protected static final int ID_PRODUCTITEM = 53;
	protected static final int ID_KITLINETRANQUANTITY = 54;
	protected static final int ID_SCHEDULETRANQUANTITY = 55;


    protected static com.haht.xml.wrapper.ContentModel[] rModels =
    {
		new com.haht.xml.wrapper.ContentModel("Order", Order.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("yfc:doc", Yfc_doc.class,  TYPE_TEXT, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLines", OrderLines.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductServiceAssocs", ProductServiceAssocs.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Notes", Notes.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Instructions", Instructions.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoShipTo", PersonInfoShipTo.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoBillTo", PersonInfoBillTo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoMarkFor", PersonInfoMarkFor.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoContact", PersonInfoContact.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AdditionalAddresses", AdditionalAddresses.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PriceInfo", PriceInfo.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderCharges", HeaderCharges.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderTaxes", HeaderTaxes.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("References", References.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PaymentMethods", PaymentMethods.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderDates", OrderDates.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("SpecialServices", SpecialServices.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderHoldTypes", OrderHoldTypes.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLine", OrderLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductServiceAssoc", ProductServiceAssoc.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Note", Note.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Instruction", Instruction.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AdditionalAddress", AdditionalAddress.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderCharge", HeaderCharge.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderTax", HeaderTax.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Reference", Reference.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PaymentMethod", PaymentMethod.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderDate", OrderDate.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("SpecialService", SpecialService.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderHoldType", OrderHoldType.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineTranQuantity", OrderLineTranQuantity.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("DerivedFrom", DerivedFrom.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineOptions", OrderLineOptions.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Item", Item.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LinePriceInfo", LinePriceInfo.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineCharges", LineCharges.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineTaxes", LineTaxes.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLines", KitLines.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Schedules", Schedules.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Dependency", Dependency.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineInvAttRequest", OrderLineInvAttRequest.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductItems", ProductItems.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("BundleParentLine", BundleParentLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductLine", ProductLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ServiceLine", ServiceLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfo", PersonInfo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PaymentDetails", PaymentDetails.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineOption", OrderLineOption.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineCharge", LineCharge.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineTax", LineTax.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLine", KitLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Schedule", Schedule.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductItem", ProductItem.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLineTranQuantity", KitLineTranQuantity.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ScheduleTranQuantity", ScheduleTranQuantity.class,  TYPE_SEQ, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTSERVICEASSOCS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_NOTES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOSHIPTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOBILLTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOMARKFOR, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOCONTACT, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRICEINFO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_HEADERCHARGES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_HEADERTAXES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REFERENCES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PAYMENTMETHODS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERDATES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SPECIALSERVICES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERHOLDTYPES, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERLINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PRODUCTSERVICEASSOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_NOTE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ null },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESS, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_HEADERCHARGE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_HEADERTAX, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_REFERENCE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PAYMENTMETHOD, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERDATE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SPECIALSERVICE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERHOLDTYPE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINETRANQUANTITY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_DERIVEDFROM, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINEOPTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ITEM, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOSHIPTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOMARKFOR, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEPRICEINFO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINECHARGES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINETAXES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REFERENCES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_KITLINES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SCHEDULES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_DEPENDENCY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERDATES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINEINVATTREQUEST, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTITEMS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_BUNDLEPARENTLINE, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTLINE, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SERVICELINE, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFO, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PAYMENTDETAILS, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERLINEOPTION, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_LINECHARGE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_LINETAX, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_KITLINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SCHEDULE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PRODUCTITEM, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_KITLINETRANQUANTITY, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SCHEDULETRANQUANTITY, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },

    };

    protected com.haht.xml.wrapper.ContentModel getContentModel(int id)
    {
		return rModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getModelItems(int id)
    {
		return rModelItems[id];
    }

    protected Class<XercesDoc> getDocumentClass()
    {
		return XercesDoc.class;
    }

    public YFSCreateOrderInputDoc(String xml) throws Exception
    {
		super(xml);
		m_Root = (Order) getRoot(ID_ORDER);
    }

    public YFSCreateOrderInputDoc(InputStream xml) throws Exception
    {
		super(xml);
		m_Root = (Order) getRoot(ID_ORDER);
    }

    public YFSCreateOrderInputDoc(Reader xml) throws Exception
    {
    	super(xml);
    	m_Root = (Order) getRoot(ID_ORDER);
    }

    public Order getOrder() { return m_Root; }
    Order m_Root;


    /////////////////////////////////////////////////////////////////////////
    // Element Classes
    /////////////////////////////////////////////////////////////////////////

	public class Order extends com.haht.xml.wrapper.Element
	{
		public Order(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDER; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public OrderLines getOrderLines() { return (OrderLines) getAtom(0, 1); }
		public ProductServiceAssocs getProductServiceAssocs() { return (ProductServiceAssocs) getAtom(0, 2); }
		public Notes getNotes() { return (Notes) getAtom(0, 3); }
		public Instructions getInstructions() { return (Instructions) getAtom(0, 4); }
		public PersonInfoShipTo getPersonInfoShipTo() { return (PersonInfoShipTo) getAtom(0, 5); }
		public PersonInfoBillTo getPersonInfoBillTo() { return (PersonInfoBillTo) getAtom(0, 6); }
		public PersonInfoMarkFor getPersonInfoMarkFor() { return (PersonInfoMarkFor) getAtom(0, 7); }
		public PersonInfoContact getPersonInfoContact() { return (PersonInfoContact) getAtom(0, 8); }
		public AdditionalAddresses getAdditionalAddresses() { return (AdditionalAddresses) getAtom(0, 9); }
		public PriceInfo getPriceInfo() { return (PriceInfo) getAtom(0, 10); }
		public HeaderCharges getHeaderCharges() { return (HeaderCharges) getAtom(0, 11); }
		public HeaderTaxes getHeaderTaxes() { return (HeaderTaxes) getAtom(0, 12); }
		public References getReferences() { return (References) getAtom(0, 13); }
		public PaymentMethods getPaymentMethods() { return (PaymentMethods) getAtom(0, 14); }
		public OrderDates getOrderDates() { return (OrderDates) getAtom(0, 15); }
		public SpecialServices getSpecialServices() { return (SpecialServices) getAtom(0, 16); }
		public OrderHoldTypes getOrderHoldTypes() { return (OrderHoldTypes) getAtom(0, 17); }
	}

	public class Yfc_doc extends com.haht.xml.wrapper.PcdataElement
	{
		public Yfc_doc(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_YFC_DOC; }
	}

	public class OrderLines extends com.haht.xml.wrapper.Element
	{
		public OrderLines(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINES; }

		public Enumeration<?> getOrderLineList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ProductServiceAssocs extends com.haht.xml.wrapper.Element
	{
		public ProductServiceAssocs(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTSERVICEASSOCS; }

		public ProductServiceAssoc getProductServiceAssoc() { return (ProductServiceAssoc) getAtom(0, 0); }
	}

	public class Notes extends com.haht.xml.wrapper.Element
	{
		public Notes(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_NOTES; }

		public Enumeration<?> getNoteList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class Instructions extends com.haht.xml.wrapper.Element
	{
		public Instructions(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INSTRUCTIONS; }

		public Enumeration<?> getInstructionList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class PersonInfoShipTo extends com.haht.xml.wrapper.Element
	{
		public PersonInfoShipTo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOSHIPTO; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class PersonInfoBillTo extends com.haht.xml.wrapper.Element
	{
		public PersonInfoBillTo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOBILLTO; }
	}

	public class PersonInfoMarkFor extends com.haht.xml.wrapper.Element
	{
		public PersonInfoMarkFor(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOMARKFOR; }
	}

	public class PersonInfoContact extends com.haht.xml.wrapper.Element
	{
		public PersonInfoContact(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOCONTACT; }
	}

	public class AdditionalAddresses extends com.haht.xml.wrapper.Element
	{
		public AdditionalAddresses(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ADDITIONALADDRESSES; }

		public Enumeration<?> getAdditionalAddressList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class PriceInfo extends com.haht.xml.wrapper.Element
	{
		public PriceInfo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRICEINFO; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class HeaderCharges extends com.haht.xml.wrapper.Element
	{
		public HeaderCharges(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_HEADERCHARGES; }

		public Enumeration<?> getHeaderChargeList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class HeaderTaxes extends com.haht.xml.wrapper.Element
	{
		public HeaderTaxes(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_HEADERTAXES; }

		public Enumeration<?> getHeaderTaxList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class References extends com.haht.xml.wrapper.Element
	{
		public References(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REFERENCES; }

		public Enumeration<?> getReferenceList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class PaymentMethods extends com.haht.xml.wrapper.Element
	{
		public PaymentMethods(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PAYMENTMETHODS; }

		public Enumeration<?> getPaymentMethodList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class OrderDates extends com.haht.xml.wrapper.Element
	{
		public OrderDates(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERDATES; }

		public Enumeration<?> getOrderDateList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class SpecialServices extends com.haht.xml.wrapper.Element
	{
		public SpecialServices(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SPECIALSERVICES; }

		public Enumeration<?> getSpecialServiceList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class OrderHoldTypes extends com.haht.xml.wrapper.Element
	{
		public OrderHoldTypes(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERHOLDTYPES; }

		public Enumeration<?> getOrderHoldTypeList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class OrderLine extends com.haht.xml.wrapper.Element
	{
		public OrderLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public OrderLineTranQuantity getOrderLineTranQuantity() { return (OrderLineTranQuantity) getAtom(0, 1); }
		public DerivedFrom getDerivedFrom() { return (DerivedFrom) getAtom(0, 2); }
		public OrderLineOptions getOrderLineOptions() { return (OrderLineOptions) getAtom(0, 3); }
		public Item getItem() { return (Item) getAtom(0, 4); }
		public PersonInfoShipTo getPersonInfoShipTo() { return (PersonInfoShipTo) getAtom(0, 5); }
		public PersonInfoMarkFor getPersonInfoMarkFor() { return (PersonInfoMarkFor) getAtom(0, 6); }
		public Instructions getInstructions() { return (Instructions) getAtom(0, 7); }
		public LinePriceInfo getLinePriceInfo() { return (LinePriceInfo) getAtom(0, 8); }
		public LineCharges getLineCharges() { return (LineCharges) getAtom(0, 9); }
		public LineTaxes getLineTaxes() { return (LineTaxes) getAtom(0, 10); }
		public References getReferences() { return (References) getAtom(0, 11); }
		public KitLines getKitLines() { return (KitLines) getAtom(0, 12); }
		public AdditionalAddresses getAdditionalAddresses() { return (AdditionalAddresses) getAtom(0, 13); }
		public Schedules getSchedules() { return (Schedules) getAtom(0, 14); }
		public Dependency getDependency() { return (Dependency) getAtom(0, 15); }
		public OrderDates getOrderDates() { return (OrderDates) getAtom(0, 16); }
		public OrderLineInvAttRequest getOrderLineInvAttRequest() { return (OrderLineInvAttRequest) getAtom(0, 17); }
		public ProductItems getProductItems() { return (ProductItems) getAtom(0, 18); }
		public BundleParentLine getBundleParentLine() { return (BundleParentLine) getAtom(0, 19); }
	}

	public class ProductServiceAssoc extends com.haht.xml.wrapper.Element
	{
		public ProductServiceAssoc(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTSERVICEASSOC; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public ProductLine getProductLine() { return (ProductLine) getAtom(0, 1); }
		public ServiceLine getServiceLine() { return (ServiceLine) getAtom(0, 2); }
	}

	public class Note extends com.haht.xml.wrapper.Element
	{
		public Note(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_NOTE; }
	}

	public class Instruction extends com.haht.xml.wrapper.Element
	{
		public Instruction(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INSTRUCTION; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class AdditionalAddress extends com.haht.xml.wrapper.Element
	{
		public AdditionalAddress(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ADDITIONALADDRESS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public PersonInfo getPersonInfo() { return (PersonInfo) getAtom(0, 1); }
	}

	public class HeaderCharge extends com.haht.xml.wrapper.Element
	{
		public HeaderCharge(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_HEADERCHARGE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class HeaderTax extends com.haht.xml.wrapper.Element
	{
		public HeaderTax(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_HEADERTAX; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class Reference extends com.haht.xml.wrapper.Element
	{
		public Reference(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REFERENCE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class PaymentMethod extends com.haht.xml.wrapper.Element
	{
		public PaymentMethod(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PAYMENTMETHOD; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public PaymentDetails getPaymentDetails() { return (PaymentDetails) getAtom(0, 1); }
	}

	public class OrderDate extends com.haht.xml.wrapper.Element
	{
		public OrderDate(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERDATE; }
	}

	public class SpecialService extends com.haht.xml.wrapper.Element
	{
		public SpecialService(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SPECIALSERVICE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class OrderHoldType extends com.haht.xml.wrapper.Element
	{
		public OrderHoldType(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERHOLDTYPE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class OrderLineTranQuantity extends com.haht.xml.wrapper.Element
	{
		public OrderLineTranQuantity(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINETRANQUANTITY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class DerivedFrom extends com.haht.xml.wrapper.Element
	{
		public DerivedFrom(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_DERIVEDFROM; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class OrderLineOptions extends com.haht.xml.wrapper.Element
	{
		public OrderLineOptions(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINEOPTIONS; }

		public OrderLineOption getOrderLineOption() { return (OrderLineOption) getAtom(0, 0); }
	}

	public class Item extends com.haht.xml.wrapper.Element
	{
		public Item(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ITEM; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LinePriceInfo extends com.haht.xml.wrapper.Element
	{
		public LinePriceInfo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEPRICEINFO; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineCharges extends com.haht.xml.wrapper.Element
	{
		public LineCharges(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINECHARGES; }

		public Enumeration<?> getLineChargeList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class LineTaxes extends com.haht.xml.wrapper.Element
	{
		public LineTaxes(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINETAXES; }

		public Enumeration<?> getLineTaxList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class KitLines extends com.haht.xml.wrapper.Element
	{
		public KitLines(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITLINES; }

		public Enumeration<?> getKitLineList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class Schedules extends com.haht.xml.wrapper.Element
	{
		public Schedules(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SCHEDULES; }

		public Enumeration<?> getScheduleList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class Dependency extends com.haht.xml.wrapper.Element
	{
		public Dependency(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_DEPENDENCY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class OrderLineInvAttRequest extends com.haht.xml.wrapper.Element
	{
		public OrderLineInvAttRequest(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINEINVATTREQUEST; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ProductItems extends com.haht.xml.wrapper.Element
	{
		public ProductItems(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTITEMS; }

		public ProductItem getProductItem() { return (ProductItem) getAtom(0, 0); }
	}

	public class BundleParentLine extends com.haht.xml.wrapper.Element
	{
		public BundleParentLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_BUNDLEPARENTLINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ProductLine extends com.haht.xml.wrapper.Element
	{
		public ProductLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTLINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ServiceLine extends com.haht.xml.wrapper.Element
	{
		public ServiceLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SERVICELINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class PersonInfo extends com.haht.xml.wrapper.Element
	{
		public PersonInfo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFO; }
	}

	public class PaymentDetails extends com.haht.xml.wrapper.Element
	{
		public PaymentDetails(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PAYMENTDETAILS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class OrderLineOption extends com.haht.xml.wrapper.Element
	{
		public OrderLineOption(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINEOPTION; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineCharge extends com.haht.xml.wrapper.Element
	{
		public LineCharge(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINECHARGE; }
	}

	public class LineTax extends com.haht.xml.wrapper.Element
	{
		public LineTax(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINETAX; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class KitLine extends com.haht.xml.wrapper.Element
	{
		public KitLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITLINE; }

		public KitLineTranQuantity getKitLineTranQuantity() { return (KitLineTranQuantity) getAtom(0, 0); }
	}

	public class Schedule extends com.haht.xml.wrapper.Element
	{
		public Schedule(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SCHEDULE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public ScheduleTranQuantity getScheduleTranQuantity() { return (ScheduleTranQuantity) getAtom(0, 1); }
	}

	public class ProductItem extends com.haht.xml.wrapper.Element
	{
		public ProductItem(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTITEM; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class KitLineTranQuantity extends com.haht.xml.wrapper.Element
	{
		public KitLineTranQuantity(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITLINETRANQUANTITY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ScheduleTranQuantity extends com.haht.xml.wrapper.Element
	{
		public ScheduleTranQuantity(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SCHEDULETRANQUANTITY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}


}
