/**
  * YFSCreateOrderOutputDoc.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.yantra.xmlwrapper;

/////////////////////////////////////////////////////////////////////////////
// IMPORTS
/////////////////////////////////////////////////////////////////////////////
import java.io.*;
import java.util.*;
import com.haht.xml.*;

public class YFSCreateOrderOutputDoc extends com.haht.xml.wrapper.Doc
{
	protected static final int ID_ORDER = 0;
	protected static final int ID_YFC_DOC = 1;
	protected static final int ID_ORDERLINES = 2;
	protected static final int ID_NOTES = 3;
	protected static final int ID_INSTRUCTIONS = 4;
	protected static final int ID_PERSONINFOSHIPTO = 5;
	protected static final int ID_PERSONINFOBILLTO = 6;
	protected static final int ID_PERSONINFOMARKFOR = 7;
	protected static final int ID_PERSONINFOCONTACT = 8;
	protected static final int ID_ADDITIONALADDRESSES = 9;
	protected static final int ID_PRICEINFO = 10;
	protected static final int ID_PRICEINFOINENTERPRISECURRENCY = 11;
	protected static final int ID_OVERALLTOTALS = 12;
	protected static final int ID_INVOICEDTOTALS = 13;
	protected static final int ID_REMAININGTOTALS = 14;
	protected static final int ID_OVERALLTOTALSINENTERPRISECURRENCY = 15;
	protected static final int ID_REMAININGTOTALSINENTERPRISECURRENCY = 16;
	protected static final int ID_HEADERCHARGES = 17;
	protected static final int ID_HEADERTAXES = 18;
	protected static final int ID_REFERENCES = 19;
	protected static final int ID_PAYMENTMETHODS = 20;
	protected static final int ID_CHARGETRANSACTIONDETAILS = 21;
	protected static final int ID_ORDERSTATUSES = 22;
	protected static final int ID_ORDERDATES = 23;
	protected static final int ID_PRODUCTSERVICEASSOCS = 24;
	protected static final int ID_SPECIALSERVICES = 25;
	protected static final int ID_ORDERLINE = 26;
	protected static final int ID_NOTE = 27;
	protected static final int ID_INSTRUCTION = 28;
	protected static final int ID_ADDITIONALADDRESS = 29;
	protected static final int ID_HEADERCHARGE = 30;
	protected static final int ID_HEADERTAX = 31;
	protected static final int ID_TAXSUMMARY = 32;
	protected static final int ID_REFERENCE = 33;
	protected static final int ID_PAYMENTMETHOD = 34;
	protected static final int ID_CHARGETRANSACTIONDETAIL = 35;
	protected static final int ID_ORDERSTATUS = 36;
	protected static final int ID_ORDERDATE = 37;
	protected static final int ID_PRODUCTSERVICEASSOC = 38;
	protected static final int ID_SPECIALSERVICE = 39;
	protected static final int ID_ITEM = 40;
	protected static final int ID_WORKORDERS = 41;
	protected static final int ID_ORDERLINETRANQUANTITY = 42;
	protected static final int ID_ORDERLINEOPTIONS = 43;
	protected static final int ID_DERIVEDFROMORDER = 44;
	protected static final int ID_LINEPRICEINFO = 45;
	protected static final int ID_KITLINES = 46;
	protected static final int ID_SCHEDULES = 47;
	protected static final int ID_LINEOVERALLTOTALS = 48;
	protected static final int ID_LINEINVOICEDTOTALS = 49;
	protected static final int ID_LINEREMAININGTOTALS = 50;
	protected static final int ID_LINEOVERALLTOTALSINENTERPRISECURRENCY = 51;
	protected static final int ID_LINEREMAININGTOTALSINENTERPRISECURRENCY = 52;
	protected static final int ID_LINECHARGES = 53;
	protected static final int ID_LINETAXES = 54;
	protected static final int ID_ORDERLINEINVATTREQUEST = 55;
	protected static final int ID_PRODUCTASSOCIATIONS = 56;
	protected static final int ID_SERVICEASSOCIATIONS = 57;
	protected static final int ID_DELIVERYASSOCIATIONS = 58;
	protected static final int ID_DERIVEDFROMORDERLINE = 59;
	protected static final int ID_PERSONINFO = 60;
	protected static final int ID_TAXSUMMARYDETAIL = 61;
	protected static final int ID_CREDITCARDTRANSACTIONS = 62;
	protected static final int ID_ORDERSTATUSTRANQUANTITY = 63;
	protected static final int ID_DETAILS = 64;
	protected static final int ID_PRODUCTLINE = 65;
	protected static final int ID_SERVICELINE = 66;
	protected static final int ID_LANGUAGEDESCRIPTIONLIST = 67;
	protected static final int ID_WORKORDER = 68;
	protected static final int ID_ORDERLINEOPTION = 69;
	protected static final int ID_KITLINE = 70;
	protected static final int ID_SCHEDULE = 71;
	protected static final int ID_LINECHARGE = 72;
	protected static final int ID_LINETAX = 73;
	protected static final int ID_PRODUCTASSOCIATION = 74;
	protected static final int ID_SERVICEASSOCIATION = 75;
	protected static final int ID_DELIVERYASSOCIATION = 76;
	protected static final int ID_CREDITCARDTRANSACTION = 77;
	protected static final int ID_KITDETAILS = 78;
	protected static final int ID_LANGUAGEDESCRIPTION = 79;
	protected static final int ID_KITLINETRANQUANTITY = 80;
	protected static final int ID_SCHEDULETRANQUANTITY = 81;
	protected static final int ID_KITDETAIL = 82;
	protected static final int ID_KITDETAILTRANQUANTITY = 83;


    protected static com.haht.xml.wrapper.ContentModel[] rModels =
    {
		new com.haht.xml.wrapper.ContentModel("Order", Order.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("yfc:doc", Yfc_doc.class,  TYPE_TEXT, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLines", OrderLines.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Notes", Notes.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Instructions", Instructions.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoShipTo", PersonInfoShipTo.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoBillTo", PersonInfoBillTo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoMarkFor", PersonInfoMarkFor.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoContact", PersonInfoContact.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AdditionalAddresses", AdditionalAddresses.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PriceInfo", PriceInfo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PriceInfoInEnterpriseCurrency", PriceInfoInEnterpriseCurrency.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OverallTotals", OverallTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("InvoicedTotals", InvoicedTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("RemainingTotals", RemainingTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OverallTotalsInEnterpriseCurrency", OverallTotalsInEnterpriseCurrency.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("RemainingTotalsInEnterpriseCurrency", RemainingTotalsInEnterpriseCurrency.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderCharges", HeaderCharges.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderTaxes", HeaderTaxes.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("References", References.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PaymentMethods", PaymentMethods.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ChargeTransactionDetails", ChargeTransactionDetails.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderStatuses", OrderStatuses.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderDates", OrderDates.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductServiceAssocs", ProductServiceAssocs.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("SpecialServices", SpecialServices.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLine", OrderLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Note", Note.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Instruction", Instruction.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AdditionalAddress", AdditionalAddress.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderCharge", HeaderCharge.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderTax", HeaderTax.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("TaxSummary", TaxSummary.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Reference", Reference.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PaymentMethod", PaymentMethod.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ChargeTransactionDetail", ChargeTransactionDetail.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderStatus", OrderStatus.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderDate", OrderDate.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductServiceAssoc", ProductServiceAssoc.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("SpecialService", SpecialService.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Item", Item.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("WorkOrders", WorkOrders.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineTranQuantity", OrderLineTranQuantity.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineOptions", OrderLineOptions.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("DerivedFromOrder", DerivedFromOrder.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LinePriceInfo", LinePriceInfo.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLines", KitLines.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Schedules", Schedules.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineOverallTotals", LineOverallTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineInvoicedTotals", LineInvoicedTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineRemainingTotals", LineRemainingTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineOverallTotalsInEnterpriseCurrency", LineOverallTotalsInEnterpriseCurrency.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineRemainingTotalsInEnterpriseCurrency", LineRemainingTotalsInEnterpriseCurrency.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineCharges", LineCharges.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineTaxes", LineTaxes.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineInvAttRequest", OrderLineInvAttRequest.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductAssociations", ProductAssociations.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ServiceAssociations", ServiceAssociations.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("DeliveryAssociations", DeliveryAssociations.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("DerivedFromOrderLine", DerivedFromOrderLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfo", PersonInfo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("TaxSummaryDetail", TaxSummaryDetail.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("CreditCardTransactions", CreditCardTransactions.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderStatusTranQuantity", OrderStatusTranQuantity.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Details", Details.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductLine", ProductLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ServiceLine", ServiceLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LanguageDescriptionList", LanguageDescriptionList.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("WorkOrder", WorkOrder.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineOption", OrderLineOption.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLine", KitLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Schedule", Schedule.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineCharge", LineCharge.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineTax", LineTax.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductAssociation", ProductAssociation.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ServiceAssociation", ServiceAssociation.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("DeliveryAssociation", DeliveryAssociation.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("CreditCardTransaction", CreditCardTransaction.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitDetails", KitDetails.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LanguageDescription", LanguageDescription.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLineTranQuantity", KitLineTranQuantity.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ScheduleTranQuantity", ScheduleTranQuantity.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitDetail", KitDetail.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitDetailTranQuantity", KitDetailTranQuantity.class,  TYPE_SEQ, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_NOTES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOSHIPTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOBILLTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOMARKFOR, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOCONTACT, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRICEINFO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRICEINFOINENTERPRISECURRENCY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_OVERALLTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INVOICEDTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REMAININGTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_OVERALLTOTALSINENTERPRISECURRENCY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REMAININGTOTALSINENTERPRISECURRENCY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_HEADERCHARGES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_HEADERTAXES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REFERENCES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PAYMENTMETHODS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_CHARGETRANSACTIONDETAILS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERSTATUSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERDATES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTSERVICEASSOCS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SPECIALSERVICES, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_NOTE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESS, QUAL_STAR) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_HEADERCHARGE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_HEADERTAX, QUAL_STAR), new com.haht.xml.wrapper.ModelItem(ID_TAXSUMMARY, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_REFERENCE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PAYMENTMETHOD, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_CHARGETRANSACTIONDETAIL, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERSTATUS, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERDATE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PRODUCTSERVICEASSOC, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SPECIALSERVICE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ITEM, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_WORKORDERS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINETRANQUANTITY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINEOPTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_DERIVEDFROMORDER, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOSHIPTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOMARKFOR, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEPRICEINFO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REFERENCES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_KITLINES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SCHEDULES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEOVERALLTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEINVOICEDTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEREMAININGTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEOVERALLTOTALSINENTERPRISECURRENCY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEREMAININGTOTALSINENTERPRISECURRENCY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINECHARGES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINETAXES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERSTATUSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERDATES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINEINVATTREQUEST, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTASSOCIATIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SERVICEASSOCIATIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_DELIVERYASSOCIATIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_DERIVEDFROMORDERLINE, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_PERSONINFO, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_TAXSUMMARYDETAIL, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_CREDITCARDTRANSACTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PAYMENTMETHOD, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERSTATUSTRANQUANTITY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_DETAILS, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_PRODUCTLINE, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SERVICELINE, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LANGUAGEDESCRIPTIONLIST, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_WORKORDER, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERLINEOPTION, QUAL_STAR) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_KITLINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SCHEDULE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_LINECHARGE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_LINETAX, QUAL_STAR), new com.haht.xml.wrapper.ModelItem(ID_TAXSUMMARY, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PRODUCTASSOCIATION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SERVICEASSOCIATION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_DELIVERYASSOCIATION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ITEM, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_CREDITCARDTRANSACTION, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_KITDETAILS, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_LANGUAGEDESCRIPTION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_KITLINETRANQUANTITY, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SCHEDULETRANQUANTITY, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTLINE, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SERVICELINE, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTLINE, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SERVICELINE, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTLINE, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SERVICELINE, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_KITDETAIL, QUAL_STAR) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_KITDETAILTRANQUANTITY, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },

    };

    protected com.haht.xml.wrapper.ContentModel getContentModel(int id)
    {
		return rModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getModelItems(int id)
    {
		return rModelItems[id];
    }

    protected Class<XercesDoc> getDocumentClass()
    {
		return XercesDoc.class;
    }

    public YFSCreateOrderOutputDoc(String xml) throws Exception
    {
		super(xml);
		m_Root = (Order) getRoot(ID_ORDER);
    }

    public YFSCreateOrderOutputDoc(InputStream xml) throws Exception
    {
		super(xml);
		m_Root = (Order) getRoot(ID_ORDER);
    }

    public YFSCreateOrderOutputDoc(Reader xml) throws Exception
    {
    	super(xml);
    	m_Root = (Order) getRoot(ID_ORDER);
    }

    public Order getOrder() { return m_Root; }
    Order m_Root;


    /////////////////////////////////////////////////////////////////////////
    // Element Classes
    /////////////////////////////////////////////////////////////////////////

	public class Order extends com.haht.xml.wrapper.Element
	{
		public Order(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDER; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public OrderLines getOrderLines() { return (OrderLines) getAtom(0, 1); }
		public Notes getNotes() { return (Notes) getAtom(0, 2); }
		public Instructions getInstructions() { return (Instructions) getAtom(0, 3); }
		public PersonInfoShipTo getPersonInfoShipTo() { return (PersonInfoShipTo) getAtom(0, 4); }
		public PersonInfoBillTo getPersonInfoBillTo() { return (PersonInfoBillTo) getAtom(0, 5); }
		public PersonInfoMarkFor getPersonInfoMarkFor() { return (PersonInfoMarkFor) getAtom(0, 6); }
		public PersonInfoContact getPersonInfoContact() { return (PersonInfoContact) getAtom(0, 7); }
		public AdditionalAddresses getAdditionalAddresses() { return (AdditionalAddresses) getAtom(0, 8); }
		public PriceInfo getPriceInfo() { return (PriceInfo) getAtom(0, 9); }
		public PriceInfoInEnterpriseCurrency getPriceInfoInEnterpriseCurrency() { return (PriceInfoInEnterpriseCurrency) getAtom(0, 10); }
		public OverallTotals getOverallTotals() { return (OverallTotals) getAtom(0, 11); }
		public InvoicedTotals getInvoicedTotals() { return (InvoicedTotals) getAtom(0, 12); }
		public RemainingTotals getRemainingTotals() { return (RemainingTotals) getAtom(0, 13); }
		public OverallTotalsInEnterpriseCurrency getOverallTotalsInEnterpriseCurrency() { return (OverallTotalsInEnterpriseCurrency) getAtom(0, 14); }
		public RemainingTotalsInEnterpriseCurrency getRemainingTotalsInEnterpriseCurrency() { return (RemainingTotalsInEnterpriseCurrency) getAtom(0, 15); }
		public HeaderCharges getHeaderCharges() { return (HeaderCharges) getAtom(0, 16); }
		public HeaderTaxes getHeaderTaxes() { return (HeaderTaxes) getAtom(0, 17); }
		public References getReferences() { return (References) getAtom(0, 18); }
		public PaymentMethods getPaymentMethods() { return (PaymentMethods) getAtom(0, 19); }
		public ChargeTransactionDetails getChargeTransactionDetails() { return (ChargeTransactionDetails) getAtom(0, 20); }
		public OrderStatuses getOrderStatuses() { return (OrderStatuses) getAtom(0, 21); }
		public OrderDates getOrderDates() { return (OrderDates) getAtom(0, 22); }
		public ProductServiceAssocs getProductServiceAssocs() { return (ProductServiceAssocs) getAtom(0, 23); }
		public SpecialServices getSpecialServices() { return (SpecialServices) getAtom(0, 24); }
	}

	public class Yfc_doc extends com.haht.xml.wrapper.PcdataElement
	{
		public Yfc_doc(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_YFC_DOC; }
	}

	public class OrderLines extends com.haht.xml.wrapper.Element
	{
		public OrderLines(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINES; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Enumeration<?> getOrderLineList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class Notes extends com.haht.xml.wrapper.Element
	{
		public Notes(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_NOTES; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Enumeration<?> getNoteList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class Instructions extends com.haht.xml.wrapper.Element
	{
		public Instructions(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INSTRUCTIONS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Enumeration<?> getInstructionList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class PersonInfoShipTo extends com.haht.xml.wrapper.Element
	{
		public PersonInfoShipTo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOSHIPTO; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class PersonInfoBillTo extends com.haht.xml.wrapper.Element
	{
		public PersonInfoBillTo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOBILLTO; }
	}

	public class PersonInfoMarkFor extends com.haht.xml.wrapper.Element
	{
		public PersonInfoMarkFor(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOMARKFOR; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class PersonInfoContact extends com.haht.xml.wrapper.Element
	{
		public PersonInfoContact(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOCONTACT; }
	}

	public class AdditionalAddresses extends com.haht.xml.wrapper.Element
	{
		public AdditionalAddresses(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ADDITIONALADDRESSES; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Enumeration<?> getAdditionalAddressList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class PriceInfo extends com.haht.xml.wrapper.Element
	{
		public PriceInfo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRICEINFO; }
	}

	public class PriceInfoInEnterpriseCurrency extends com.haht.xml.wrapper.Element
	{
		public PriceInfoInEnterpriseCurrency(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRICEINFOINENTERPRISECURRENCY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class OverallTotals extends com.haht.xml.wrapper.Element
	{
		public OverallTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_OVERALLTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class InvoicedTotals extends com.haht.xml.wrapper.Element
	{
		public InvoicedTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INVOICEDTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class RemainingTotals extends com.haht.xml.wrapper.Element
	{
		public RemainingTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REMAININGTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class OverallTotalsInEnterpriseCurrency extends com.haht.xml.wrapper.Element
	{
		public OverallTotalsInEnterpriseCurrency(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_OVERALLTOTALSINENTERPRISECURRENCY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class RemainingTotalsInEnterpriseCurrency extends com.haht.xml.wrapper.Element
	{
		public RemainingTotalsInEnterpriseCurrency(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REMAININGTOTALSINENTERPRISECURRENCY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class HeaderCharges extends com.haht.xml.wrapper.Element
	{
		public HeaderCharges(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_HEADERCHARGES; }

		public Enumeration<?> getHeaderChargeList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class HeaderTaxes extends com.haht.xml.wrapper.Element
	{
		public HeaderTaxes(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_HEADERTAXES; }

		public Enumeration<?> getHeaderTaxList() { return getAtomList(0, 0).getAtoms(); }
		public TaxSummary getTaxSummary() { return (TaxSummary) getAtom(0, 1); }
	}

	public class References extends com.haht.xml.wrapper.Element
	{
		public References(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REFERENCES; }

		public Enumeration<?> getReferenceList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class PaymentMethods extends com.haht.xml.wrapper.Element
	{
		public PaymentMethods(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PAYMENTMETHODS; }

		public Enumeration<?> getPaymentMethodList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ChargeTransactionDetails extends com.haht.xml.wrapper.Element
	{
		public ChargeTransactionDetails(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CHARGETRANSACTIONDETAILS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Enumeration<?> getChargeTransactionDetailList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class OrderStatuses extends com.haht.xml.wrapper.Element
	{
		public OrderStatuses(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERSTATUSES; }

		public Enumeration<?> getOrderStatusList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class OrderDates extends com.haht.xml.wrapper.Element
	{
		public OrderDates(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERDATES; }

		public Enumeration<?> getOrderDateList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ProductServiceAssocs extends com.haht.xml.wrapper.Element
	{
		public ProductServiceAssocs(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTSERVICEASSOCS; }

		public Enumeration<?> getProductServiceAssocList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class SpecialServices extends com.haht.xml.wrapper.Element
	{
		public SpecialServices(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SPECIALSERVICES; }

		public Enumeration<?> getSpecialServiceList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class OrderLine extends com.haht.xml.wrapper.Element
	{
		public OrderLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Item getItem() { return (Item) getAtom(0, 1); }
		public WorkOrders getWorkOrders() { return (WorkOrders) getAtom(0, 2); }
		public OrderLineTranQuantity getOrderLineTranQuantity() { return (OrderLineTranQuantity) getAtom(0, 3); }
		public OrderLineOptions getOrderLineOptions() { return (OrderLineOptions) getAtom(0, 4); }
		public DerivedFromOrder getDerivedFromOrder() { return (DerivedFromOrder) getAtom(0, 5); }
		public PersonInfoShipTo getPersonInfoShipTo() { return (PersonInfoShipTo) getAtom(0, 6); }
		public PersonInfoMarkFor getPersonInfoMarkFor() { return (PersonInfoMarkFor) getAtom(0, 7); }
		public LinePriceInfo getLinePriceInfo() { return (LinePriceInfo) getAtom(0, 8); }
		public Instructions getInstructions() { return (Instructions) getAtom(0, 9); }
		public References getReferences() { return (References) getAtom(0, 10); }
		public KitLines getKitLines() { return (KitLines) getAtom(0, 11); }
		public Schedules getSchedules() { return (Schedules) getAtom(0, 12); }
		public AdditionalAddresses getAdditionalAddresses() { return (AdditionalAddresses) getAtom(0, 13); }
		public LineOverallTotals getLineOverallTotals() { return (LineOverallTotals) getAtom(0, 14); }
		public LineInvoicedTotals getLineInvoicedTotals() { return (LineInvoicedTotals) getAtom(0, 15); }
		public LineRemainingTotals getLineRemainingTotals() { return (LineRemainingTotals) getAtom(0, 16); }
		public LineOverallTotalsInEnterpriseCurrency getLineOverallTotalsInEnterpriseCurrency() { return (LineOverallTotalsInEnterpriseCurrency) getAtom(0, 17); }
		public LineRemainingTotalsInEnterpriseCurrency getLineRemainingTotalsInEnterpriseCurrency() { return (LineRemainingTotalsInEnterpriseCurrency) getAtom(0, 18); }
		public LineCharges getLineCharges() { return (LineCharges) getAtom(0, 19); }
		public LineTaxes getLineTaxes() { return (LineTaxes) getAtom(0, 20); }
		public OrderStatuses getOrderStatuses() { return (OrderStatuses) getAtom(0, 21); }
		public OrderDates getOrderDates() { return (OrderDates) getAtom(0, 22); }
		public OrderLineInvAttRequest getOrderLineInvAttRequest() { return (OrderLineInvAttRequest) getAtom(0, 23); }
		public ProductAssociations getProductAssociations() { return (ProductAssociations) getAtom(0, 24); }
		public ServiceAssociations getServiceAssociations() { return (ServiceAssociations) getAtom(0, 25); }
		public DeliveryAssociations getDeliveryAssociations() { return (DeliveryAssociations) getAtom(0, 26); }
		public DerivedFromOrderLine getDerivedFromOrderLine() { return (DerivedFromOrderLine) getAtom(0, 27); }
	}

	public class Note extends com.haht.xml.wrapper.Element
	{
		public Note(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_NOTE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class Instruction extends com.haht.xml.wrapper.Element
	{
		public Instruction(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INSTRUCTION; }
	}

	public class AdditionalAddress extends com.haht.xml.wrapper.Element
	{
		public AdditionalAddress(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ADDITIONALADDRESS; }

		public PersonInfo getPersonInfo() { return (PersonInfo) getAtom(0, 0); }
	}

	public class HeaderCharge extends com.haht.xml.wrapper.Element
	{
		public HeaderCharge(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_HEADERCHARGE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class HeaderTax extends com.haht.xml.wrapper.Element
	{
		public HeaderTax(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_HEADERTAX; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class TaxSummary extends com.haht.xml.wrapper.Element
	{
		public TaxSummary(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_TAXSUMMARY; }

		public TaxSummaryDetail getTaxSummaryDetail() { return (TaxSummaryDetail) getAtom(0, 0); }
	}

	public class Reference extends com.haht.xml.wrapper.Element
	{
		public Reference(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REFERENCE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class PaymentMethod extends com.haht.xml.wrapper.Element
	{
		public PaymentMethod(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PAYMENTMETHOD; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ChargeTransactionDetail extends com.haht.xml.wrapper.Element
	{
		public ChargeTransactionDetail(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CHARGETRANSACTIONDETAIL; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public CreditCardTransactions getCreditCardTransactions() { return (CreditCardTransactions) getAtom(0, 1); }
		public PaymentMethod getPaymentMethod() { return (PaymentMethod) getAtom(0, 2); }
	}

	public class OrderStatus extends com.haht.xml.wrapper.Element
	{
		public OrderStatus(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERSTATUS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public OrderStatusTranQuantity getOrderStatusTranQuantity() { return (OrderStatusTranQuantity) getAtom(0, 1); }
		public Details getDetails() { return (Details) getAtom(0, 2); }
	}

	public class OrderDate extends com.haht.xml.wrapper.Element
	{
		public OrderDate(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERDATE; }
	}

	public class ProductServiceAssoc extends com.haht.xml.wrapper.Element
	{
		public ProductServiceAssoc(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTSERVICEASSOC; }

		public ProductLine getProductLine() { return (ProductLine) getAtom(0, 0); }
		public ServiceLine getServiceLine() { return (ServiceLine) getAtom(0, 1); }
	}

	public class SpecialService extends com.haht.xml.wrapper.Element
	{
		public SpecialService(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SPECIALSERVICE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class Item extends com.haht.xml.wrapper.Element
	{
		public Item(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ITEM; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public LanguageDescriptionList getLanguageDescriptionList() { return (LanguageDescriptionList) getAtom(0, 1); }
	}

	public class WorkOrders extends com.haht.xml.wrapper.Element
	{
		public WorkOrders(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_WORKORDERS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Enumeration<?> getWorkOrderList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class OrderLineTranQuantity extends com.haht.xml.wrapper.Element
	{
		public OrderLineTranQuantity(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINETRANQUANTITY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class OrderLineOptions extends com.haht.xml.wrapper.Element
	{
		public OrderLineOptions(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINEOPTIONS; }

		public Enumeration<?> getOrderLineOptionList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class DerivedFromOrder extends com.haht.xml.wrapper.Element
	{
		public DerivedFromOrder(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_DERIVEDFROMORDER; }
	}

	public class LinePriceInfo extends com.haht.xml.wrapper.Element
	{
		public LinePriceInfo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEPRICEINFO; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class KitLines extends com.haht.xml.wrapper.Element
	{
		public KitLines(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITLINES; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Enumeration<?> getKitLineList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class Schedules extends com.haht.xml.wrapper.Element
	{
		public Schedules(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SCHEDULES; }

		public Enumeration<?> getScheduleList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class LineOverallTotals extends com.haht.xml.wrapper.Element
	{
		public LineOverallTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEOVERALLTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineInvoicedTotals extends com.haht.xml.wrapper.Element
	{
		public LineInvoicedTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEINVOICEDTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineRemainingTotals extends com.haht.xml.wrapper.Element
	{
		public LineRemainingTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEREMAININGTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineOverallTotalsInEnterpriseCurrency extends com.haht.xml.wrapper.Element
	{
		public LineOverallTotalsInEnterpriseCurrency(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEOVERALLTOTALSINENTERPRISECURRENCY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineRemainingTotalsInEnterpriseCurrency extends com.haht.xml.wrapper.Element
	{
		public LineRemainingTotalsInEnterpriseCurrency(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEREMAININGTOTALSINENTERPRISECURRENCY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineCharges extends com.haht.xml.wrapper.Element
	{
		public LineCharges(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINECHARGES; }

		public Enumeration<?> getLineChargeList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class LineTaxes extends com.haht.xml.wrapper.Element
	{
		public LineTaxes(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINETAXES; }

		public Enumeration<?> getLineTaxList() { return getAtomList(0, 0).getAtoms(); }
		public TaxSummary getTaxSummary() { return (TaxSummary) getAtom(0, 1); }
	}

	public class OrderLineInvAttRequest extends com.haht.xml.wrapper.Element
	{
		public OrderLineInvAttRequest(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINEINVATTREQUEST; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ProductAssociations extends com.haht.xml.wrapper.Element
	{
		public ProductAssociations(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTASSOCIATIONS; }

		public Enumeration<?> getProductAssociationList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ServiceAssociations extends com.haht.xml.wrapper.Element
	{
		public ServiceAssociations(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SERVICEASSOCIATIONS; }

		public Enumeration<?> getServiceAssociationList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class DeliveryAssociations extends com.haht.xml.wrapper.Element
	{
		public DeliveryAssociations(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_DELIVERYASSOCIATIONS; }

		public Enumeration<?> getDeliveryAssociationList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class DerivedFromOrderLine extends com.haht.xml.wrapper.Element
	{
		public DerivedFromOrderLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_DERIVEDFROMORDERLINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Item getItem() { return (Item) getAtom(0, 1); }
	}

	public class PersonInfo extends com.haht.xml.wrapper.Element
	{
		public PersonInfo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFO; }
	}

	public class TaxSummaryDetail extends com.haht.xml.wrapper.Element
	{
		public TaxSummaryDetail(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_TAXSUMMARYDETAIL; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class CreditCardTransactions extends com.haht.xml.wrapper.Element
	{
		public CreditCardTransactions(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CREDITCARDTRANSACTIONS; }

		public CreditCardTransaction getCreditCardTransaction() { return (CreditCardTransaction) getAtom(0, 0); }
	}

	public class OrderStatusTranQuantity extends com.haht.xml.wrapper.Element
	{
		public OrderStatusTranQuantity(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERSTATUSTRANQUANTITY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class Details extends com.haht.xml.wrapper.Element
	{
		public Details(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_DETAILS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public KitDetails getKitDetails() { return (KitDetails) getAtom(0, 1); }
	}

	public class ProductLine extends com.haht.xml.wrapper.Element
	{
		public ProductLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTLINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ServiceLine extends com.haht.xml.wrapper.Element
	{
		public ServiceLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SERVICELINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LanguageDescriptionList extends com.haht.xml.wrapper.Element
	{
		public LanguageDescriptionList(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LANGUAGEDESCRIPTIONLIST; }

		public Enumeration<?> getLanguageDescriptionList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class WorkOrder extends com.haht.xml.wrapper.Element
	{
		public WorkOrder(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_WORKORDER; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class OrderLineOption extends com.haht.xml.wrapper.Element
	{
		public OrderLineOption(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINEOPTION; }
	}

	public class KitLine extends com.haht.xml.wrapper.Element
	{
		public KitLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITLINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public KitLineTranQuantity getKitLineTranQuantity() { return (KitLineTranQuantity) getAtom(0, 1); }
	}

	public class Schedule extends com.haht.xml.wrapper.Element
	{
		public Schedule(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SCHEDULE; }

		public ScheduleTranQuantity getScheduleTranQuantity() { return (ScheduleTranQuantity) getAtom(0, 0); }
	}

	public class LineCharge extends com.haht.xml.wrapper.Element
	{
		public LineCharge(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINECHARGE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineTax extends com.haht.xml.wrapper.Element
	{
		public LineTax(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINETAX; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ProductAssociation extends com.haht.xml.wrapper.Element
	{
		public ProductAssociation(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTASSOCIATION; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public ProductLine getProductLine() { return (ProductLine) getAtom(0, 1); }
		public ServiceLine getServiceLine() { return (ServiceLine) getAtom(0, 2); }
	}

	public class ServiceAssociation extends com.haht.xml.wrapper.Element
	{
		public ServiceAssociation(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SERVICEASSOCIATION; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public ProductLine getProductLine() { return (ProductLine) getAtom(0, 1); }
		public ServiceLine getServiceLine() { return (ServiceLine) getAtom(0, 2); }
	}

	public class DeliveryAssociation extends com.haht.xml.wrapper.Element
	{
		public DeliveryAssociation(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_DELIVERYASSOCIATION; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public ProductLine getProductLine() { return (ProductLine) getAtom(0, 1); }
		public ServiceLine getServiceLine() { return (ServiceLine) getAtom(0, 2); }
	}

	public class CreditCardTransaction extends com.haht.xml.wrapper.Element
	{
		public CreditCardTransaction(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CREDITCARDTRANSACTION; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class KitDetails extends com.haht.xml.wrapper.Element
	{
		public KitDetails(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITDETAILS; }

		public Enumeration<?> getKitDetailList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class LanguageDescription extends com.haht.xml.wrapper.Element
	{
		public LanguageDescription(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LANGUAGEDESCRIPTION; }
	}

	public class KitLineTranQuantity extends com.haht.xml.wrapper.Element
	{
		public KitLineTranQuantity(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITLINETRANQUANTITY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ScheduleTranQuantity extends com.haht.xml.wrapper.Element
	{
		public ScheduleTranQuantity(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SCHEDULETRANQUANTITY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class KitDetail extends com.haht.xml.wrapper.Element
	{
		public KitDetail(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITDETAIL; }

		public KitDetailTranQuantity getKitDetailTranQuantity() { return (KitDetailTranQuantity) getAtom(0, 0); }
	}

	public class KitDetailTranQuantity extends com.haht.xml.wrapper.Element
	{
		public KitDetailTranQuantity(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITDETAILTRANQUANTITY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}


}
