/**
  * YFSDoOrderPricingInputDoc.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.yantra.xmlwrapper;

/////////////////////////////////////////////////////////////////////////////
// IMPORTS
/////////////////////////////////////////////////////////////////////////////
import java.io.*;
import java.util.*;
import com.haht.xml.*;

public class YFSDoOrderPricingInputDoc extends com.haht.xml.wrapper.Doc
{
	protected static final int ID_ORDER = 0;
	protected static final int ID_ORDERLINES = 1;
	protected static final int ID_NOTES = 2;
	protected static final int ID_INSTRUCTIONS = 3;
	protected static final int ID_PERSONINFOSHIPTO = 4;
	protected static final int ID_PERSONINFOBILLTO = 5;
	protected static final int ID_PERSONINFOMARKFOR = 6;
	protected static final int ID_PERSONINFOCONTACT = 7;
	protected static final int ID_ADDITIONALADDRESSES = 8;
	protected static final int ID_PRICEINFO = 9;
	protected static final int ID_PRICEINFOINENTERPRISECURRENCY = 10;
	protected static final int ID_OVERALLTOTALS = 11;
	protected static final int ID_INVOICEDTOTALS = 12;
	protected static final int ID_REMAININGTOTALS = 13;
	protected static final int ID_OVERALLTOTALSINENTERPRISECURRENCY = 14;
	protected static final int ID_REMAININGTOTALSINENTERPRISECURRENCY = 15;
	protected static final int ID_HEADERCHARGES = 16;
	protected static final int ID_HEADERTAXES = 17;
	protected static final int ID_REFERENCES = 18;
	protected static final int ID_PAYMENTMETHODS = 19;
	protected static final int ID_CHARGETRANSACTIONDETAILS = 20;
	protected static final int ID_ORDERSTATUSES = 21;
	protected static final int ID_ORDERDATES = 22;
	protected static final int ID_ORDERLINE = 23;
	protected static final int ID_YFC_DOC = 24;
	protected static final int ID_NOTE = 25;
	protected static final int ID_INSTRUCTION = 26;
	protected static final int ID_ADDITIONALADDRESS = 27;
	protected static final int ID_HEADERCHARGE = 28;
	protected static final int ID_HEADERTAX = 29;
	protected static final int ID_TAXSUMMARY = 30;
	protected static final int ID_REFERENCE = 31;
	protected static final int ID_PAYMENTMETHOD = 32;
	protected static final int ID_CHARGETRANSACTIONDETAIL = 33;
	protected static final int ID_ORDERSTATUS = 34;
	protected static final int ID_ORDERDATE = 35;
	protected static final int ID_ITEM = 36;
	protected static final int ID_LINEPRICEINFO = 37;
	protected static final int ID_KITLINES = 38;
	protected static final int ID_SCHEDULES = 39;
	protected static final int ID_LINEOVERALLTOTALS = 40;
	protected static final int ID_LINEINVOICEDTOTALS = 41;
	protected static final int ID_LINEREMAININGTOTALS = 42;
	protected static final int ID_LINEOVERALLTOTALSINENTERPRISECURRENCY = 43;
	protected static final int ID_LINEREMAININGTOTALSINENTERPRISECURRENCY = 44;
	protected static final int ID_LINECHARGES = 45;
	protected static final int ID_LINETAXES = 46;
	protected static final int ID_PERSONINFO = 47;
	protected static final int ID_TAXSUMMARYDETAIL = 48;
	protected static final int ID_CREDITCARDTRANSACTIONS = 49;
	protected static final int ID_DETAILS = 50;
	protected static final int ID_LANGUAGEDESCRIPTIONLIST = 51;
	protected static final int ID_KITLINE = 52;
	protected static final int ID_SCHEDULE = 53;
	protected static final int ID_LINECHARGE = 54;
	protected static final int ID_LINETAX = 55;
	protected static final int ID_CREDITCARDTRANSACTION = 56;
	protected static final int ID_KITDETAILS = 57;
	protected static final int ID_LANGUAGEDESCRIPTION = 58;
	protected static final int ID_KITDETAIL = 59;


    protected static com.haht.xml.wrapper.ContentModel[] rModels =
    {
		new com.haht.xml.wrapper.ContentModel("Order", Order.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLines", OrderLines.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Notes", Notes.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Instructions", Instructions.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoShipTo", PersonInfoShipTo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoBillTo", PersonInfoBillTo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoMarkFor", PersonInfoMarkFor.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoContact", PersonInfoContact.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AdditionalAddresses", AdditionalAddresses.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PriceInfo", PriceInfo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PriceInfoInEnterpriseCurrency", PriceInfoInEnterpriseCurrency.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OverallTotals", OverallTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("InvoicedTotals", InvoicedTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("RemainingTotals", RemainingTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OverallTotalsInEnterpriseCurrency", OverallTotalsInEnterpriseCurrency.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("RemainingTotalsInEnterpriseCurrency", RemainingTotalsInEnterpriseCurrency.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderCharges", HeaderCharges.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderTaxes", HeaderTaxes.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("References", References.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PaymentMethods", PaymentMethods.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ChargeTransactionDetails", ChargeTransactionDetails.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderStatuses", OrderStatuses.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderDates", OrderDates.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLine", OrderLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("yfc:doc", Yfc_doc.class,  TYPE_TEXT, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Note", Note.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Instruction", Instruction.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AdditionalAddress", AdditionalAddress.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderCharge", HeaderCharge.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("HeaderTax", HeaderTax.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("TaxSummary", TaxSummary.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Reference", Reference.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PaymentMethod", PaymentMethod.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ChargeTransactionDetail", ChargeTransactionDetail.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderStatus", OrderStatus.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderDate", OrderDate.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Item", Item.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LinePriceInfo", LinePriceInfo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLines", KitLines.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Schedules", Schedules.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineOverallTotals", LineOverallTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineInvoicedTotals", LineInvoicedTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineRemainingTotals", LineRemainingTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineOverallTotalsInEnterpriseCurrency", LineOverallTotalsInEnterpriseCurrency.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineRemainingTotalsInEnterpriseCurrency", LineRemainingTotalsInEnterpriseCurrency.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineCharges", LineCharges.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineTaxes", LineTaxes.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfo", PersonInfo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("TaxSummaryDetail", TaxSummaryDetail.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("CreditCardTransactions", CreditCardTransactions.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Details", Details.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LanguageDescriptionList", LanguageDescriptionList.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLine", KitLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Schedule", Schedule.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineCharge", LineCharge.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineTax", LineTax.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("CreditCardTransaction", CreditCardTransaction.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitDetails", KitDetails.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LanguageDescription", LanguageDescription.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitDetail", KitDetail.class,  TYPE_EMPTY, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERLINES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_NOTES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOSHIPTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOBILLTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOMARKFOR, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOCONTACT, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRICEINFO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRICEINFOINENTERPRISECURRENCY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_OVERALLTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INVOICEDTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REMAININGTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_OVERALLTOTALSINENTERPRISECURRENCY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REMAININGTOTALSINENTERPRISECURRENCY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_HEADERCHARGES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_HEADERTAXES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REFERENCES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PAYMENTMETHODS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_CHARGETRANSACTIONDETAILS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERSTATUSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERDATES, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERLINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_NOTE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTION, QUAL_STAR) },
		{ null },
		{ null },
		{ null },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESS, QUAL_STAR) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_HEADERCHARGE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_HEADERTAX, QUAL_STAR), new com.haht.xml.wrapper.ModelItem(ID_TAXSUMMARY, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_REFERENCE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PAYMENTMETHOD, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_CHARGETRANSACTIONDETAIL, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERSTATUS, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERDATE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ITEM, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOSHIPTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOMARKFOR, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEPRICEINFO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REFERENCES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_KITLINES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SCHEDULES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEOVERALLTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEINVOICEDTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEREMAININGTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEOVERALLTOTALSINENTERPRISECURRENCY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEREMAININGTOTALSINENTERPRISECURRENCY, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINECHARGES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINETAXES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERSTATUSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERDATES, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_PERSONINFO, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_TAXSUMMARYDETAIL, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_CREDITCARDTRANSACTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PAYMENTMETHOD, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_DETAILS, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LANGUAGEDESCRIPTIONLIST, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_KITLINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SCHEDULE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_LINECHARGE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_LINETAX, QUAL_STAR), new com.haht.xml.wrapper.ModelItem(ID_TAXSUMMARY, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_CREDITCARDTRANSACTION, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_KITDETAILS, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_LANGUAGEDESCRIPTION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_KITDETAIL, QUAL_HOOK) },
		{ null },
		{ null },

    };

    protected com.haht.xml.wrapper.ContentModel getContentModel(int id)
    {
		return rModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getModelItems(int id)
    {
		return rModelItems[id];
    }

    protected Class<XercesDoc> getDocumentClass()
    {
		return XercesDoc.class;
    }

    public YFSDoOrderPricingInputDoc(String xml) throws Exception
    {
		super(xml);
		m_Root = (Order) getRoot(ID_ORDER);
    }

    public YFSDoOrderPricingInputDoc(InputStream xml) throws Exception
    {
		super(xml);
		m_Root = (Order) getRoot(ID_ORDER);
    }

    public YFSDoOrderPricingInputDoc(Reader xml) throws Exception
    {
    	super(xml);
    	m_Root = (Order) getRoot(ID_ORDER);
    }

    public Order getOrder() { return m_Root; }
    Order m_Root;


    /////////////////////////////////////////////////////////////////////////
    // Element Classes
    /////////////////////////////////////////////////////////////////////////

	public class Order extends com.haht.xml.wrapper.Element
	{
		public Order(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDER; }

		public OrderLines getOrderLines() { return (OrderLines) getAtom(0, 0); }
		public Notes getNotes() { return (Notes) getAtom(0, 1); }
		public Instructions getInstructions() { return (Instructions) getAtom(0, 2); }
		public PersonInfoShipTo getPersonInfoShipTo() { return (PersonInfoShipTo) getAtom(0, 3); }
		public PersonInfoBillTo getPersonInfoBillTo() { return (PersonInfoBillTo) getAtom(0, 4); }
		public PersonInfoMarkFor getPersonInfoMarkFor() { return (PersonInfoMarkFor) getAtom(0, 5); }
		public PersonInfoContact getPersonInfoContact() { return (PersonInfoContact) getAtom(0, 6); }
		public AdditionalAddresses getAdditionalAddresses() { return (AdditionalAddresses) getAtom(0, 7); }
		public PriceInfo getPriceInfo() { return (PriceInfo) getAtom(0, 8); }
		public PriceInfoInEnterpriseCurrency getPriceInfoInEnterpriseCurrency() { return (PriceInfoInEnterpriseCurrency) getAtom(0, 9); }
		public OverallTotals getOverallTotals() { return (OverallTotals) getAtom(0, 10); }
		public InvoicedTotals getInvoicedTotals() { return (InvoicedTotals) getAtom(0, 11); }
		public RemainingTotals getRemainingTotals() { return (RemainingTotals) getAtom(0, 12); }
		public OverallTotalsInEnterpriseCurrency getOverallTotalsInEnterpriseCurrency() { return (OverallTotalsInEnterpriseCurrency) getAtom(0, 13); }
		public RemainingTotalsInEnterpriseCurrency getRemainingTotalsInEnterpriseCurrency() { return (RemainingTotalsInEnterpriseCurrency) getAtom(0, 14); }
		public HeaderCharges getHeaderCharges() { return (HeaderCharges) getAtom(0, 15); }
		public HeaderTaxes getHeaderTaxes() { return (HeaderTaxes) getAtom(0, 16); }
		public References getReferences() { return (References) getAtom(0, 17); }
		public PaymentMethods getPaymentMethods() { return (PaymentMethods) getAtom(0, 18); }
		public ChargeTransactionDetails getChargeTransactionDetails() { return (ChargeTransactionDetails) getAtom(0, 19); }
		public OrderStatuses getOrderStatuses() { return (OrderStatuses) getAtom(0, 20); }
		public OrderDates getOrderDates() { return (OrderDates) getAtom(0, 21); }
	}

	public class OrderLines extends com.haht.xml.wrapper.Element
	{
		public OrderLines(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINES; }

		public Enumeration<?> getOrderLineList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class Notes extends com.haht.xml.wrapper.Element
	{
		public Notes(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_NOTES; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Enumeration<?> getNoteList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class Instructions extends com.haht.xml.wrapper.Element
	{
		public Instructions(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INSTRUCTIONS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Enumeration<?> getInstructionList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class PersonInfoShipTo extends com.haht.xml.wrapper.Element
	{
		public PersonInfoShipTo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOSHIPTO; }
	}

	public class PersonInfoBillTo extends com.haht.xml.wrapper.Element
	{
		public PersonInfoBillTo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOBILLTO; }
	}

	public class PersonInfoMarkFor extends com.haht.xml.wrapper.Element
	{
		public PersonInfoMarkFor(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOMARKFOR; }
	}

	public class PersonInfoContact extends com.haht.xml.wrapper.Element
	{
		public PersonInfoContact(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOCONTACT; }
	}

	public class AdditionalAddresses extends com.haht.xml.wrapper.Element
	{
		public AdditionalAddresses(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ADDITIONALADDRESSES; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Enumeration<?> getAdditionalAddressList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class PriceInfo extends com.haht.xml.wrapper.Element
	{
		public PriceInfo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRICEINFO; }
	}

	public class PriceInfoInEnterpriseCurrency extends com.haht.xml.wrapper.Element
	{
		public PriceInfoInEnterpriseCurrency(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRICEINFOINENTERPRISECURRENCY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class OverallTotals extends com.haht.xml.wrapper.Element
	{
		public OverallTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_OVERALLTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class InvoicedTotals extends com.haht.xml.wrapper.Element
	{
		public InvoicedTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INVOICEDTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class RemainingTotals extends com.haht.xml.wrapper.Element
	{
		public RemainingTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REMAININGTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class OverallTotalsInEnterpriseCurrency extends com.haht.xml.wrapper.Element
	{
		public OverallTotalsInEnterpriseCurrency(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_OVERALLTOTALSINENTERPRISECURRENCY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class RemainingTotalsInEnterpriseCurrency extends com.haht.xml.wrapper.Element
	{
		public RemainingTotalsInEnterpriseCurrency(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REMAININGTOTALSINENTERPRISECURRENCY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class HeaderCharges extends com.haht.xml.wrapper.Element
	{
		public HeaderCharges(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_HEADERCHARGES; }

		public Enumeration<?> getHeaderChargeList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class HeaderTaxes extends com.haht.xml.wrapper.Element
	{
		public HeaderTaxes(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_HEADERTAXES; }

		public Enumeration<?> getHeaderTaxList() { return getAtomList(0, 0).getAtoms(); }
		public TaxSummary getTaxSummary() { return (TaxSummary) getAtom(0, 1); }
	}

	public class References extends com.haht.xml.wrapper.Element
	{
		public References(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REFERENCES; }

		public Enumeration<?> getReferenceList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class PaymentMethods extends com.haht.xml.wrapper.Element
	{
		public PaymentMethods(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PAYMENTMETHODS; }

		public Enumeration<?> getPaymentMethodList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ChargeTransactionDetails extends com.haht.xml.wrapper.Element
	{
		public ChargeTransactionDetails(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CHARGETRANSACTIONDETAILS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Enumeration<?> getChargeTransactionDetailList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class OrderStatuses extends com.haht.xml.wrapper.Element
	{
		public OrderStatuses(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERSTATUSES; }

		public Enumeration<?> getOrderStatusList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class OrderDates extends com.haht.xml.wrapper.Element
	{
		public OrderDates(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERDATES; }

		public Enumeration<?> getOrderDateList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class OrderLine extends com.haht.xml.wrapper.Element
	{
		public OrderLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Item getItem() { return (Item) getAtom(0, 1); }
		public PersonInfoShipTo getPersonInfoShipTo() { return (PersonInfoShipTo) getAtom(0, 2); }
		public PersonInfoMarkFor getPersonInfoMarkFor() { return (PersonInfoMarkFor) getAtom(0, 3); }
		public LinePriceInfo getLinePriceInfo() { return (LinePriceInfo) getAtom(0, 4); }
		public Instructions getInstructions() { return (Instructions) getAtom(0, 5); }
		public References getReferences() { return (References) getAtom(0, 6); }
		public KitLines getKitLines() { return (KitLines) getAtom(0, 7); }
		public Schedules getSchedules() { return (Schedules) getAtom(0, 8); }
		public AdditionalAddresses getAdditionalAddresses() { return (AdditionalAddresses) getAtom(0, 9); }
		public LineOverallTotals getLineOverallTotals() { return (LineOverallTotals) getAtom(0, 10); }
		public LineInvoicedTotals getLineInvoicedTotals() { return (LineInvoicedTotals) getAtom(0, 11); }
		public LineRemainingTotals getLineRemainingTotals() { return (LineRemainingTotals) getAtom(0, 12); }
		public LineOverallTotalsInEnterpriseCurrency getLineOverallTotalsInEnterpriseCurrency() { return (LineOverallTotalsInEnterpriseCurrency) getAtom(0, 13); }
		public LineRemainingTotalsInEnterpriseCurrency getLineRemainingTotalsInEnterpriseCurrency() { return (LineRemainingTotalsInEnterpriseCurrency) getAtom(0, 14); }
		public LineCharges getLineCharges() { return (LineCharges) getAtom(0, 15); }
		public LineTaxes getLineTaxes() { return (LineTaxes) getAtom(0, 16); }
		public OrderStatuses getOrderStatuses() { return (OrderStatuses) getAtom(0, 17); }
		public OrderDates getOrderDates() { return (OrderDates) getAtom(0, 18); }
	}

	public class Yfc_doc extends com.haht.xml.wrapper.PcdataElement
	{
		public Yfc_doc(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_YFC_DOC; }
	}

	public class Note extends com.haht.xml.wrapper.Element
	{
		public Note(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_NOTE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class Instruction extends com.haht.xml.wrapper.Element
	{
		public Instruction(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INSTRUCTION; }
	}

	public class AdditionalAddress extends com.haht.xml.wrapper.Element
	{
		public AdditionalAddress(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ADDITIONALADDRESS; }

		public PersonInfo getPersonInfo() { return (PersonInfo) getAtom(0, 0); }
	}

	public class HeaderCharge extends com.haht.xml.wrapper.Element
	{
		public HeaderCharge(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_HEADERCHARGE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class HeaderTax extends com.haht.xml.wrapper.Element
	{
		public HeaderTax(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_HEADERTAX; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class TaxSummary extends com.haht.xml.wrapper.Element
	{
		public TaxSummary(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_TAXSUMMARY; }

		public TaxSummaryDetail getTaxSummaryDetail() { return (TaxSummaryDetail) getAtom(0, 0); }
	}

	public class Reference extends com.haht.xml.wrapper.Element
	{
		public Reference(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REFERENCE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class PaymentMethod extends com.haht.xml.wrapper.Element
	{
		public PaymentMethod(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PAYMENTMETHOD; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class ChargeTransactionDetail extends com.haht.xml.wrapper.Element
	{
		public ChargeTransactionDetail(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CHARGETRANSACTIONDETAIL; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public CreditCardTransactions getCreditCardTransactions() { return (CreditCardTransactions) getAtom(0, 1); }
		public PaymentMethod getPaymentMethod() { return (PaymentMethod) getAtom(0, 2); }
	}

	public class OrderStatus extends com.haht.xml.wrapper.Element
	{
		public OrderStatus(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERSTATUS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Details getDetails() { return (Details) getAtom(0, 1); }
	}

	public class OrderDate extends com.haht.xml.wrapper.Element
	{
		public OrderDate(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERDATE; }
	}

	public class Item extends com.haht.xml.wrapper.Element
	{
		public Item(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ITEM; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public LanguageDescriptionList getLanguageDescriptionList() { return (LanguageDescriptionList) getAtom(0, 1); }
	}

	public class LinePriceInfo extends com.haht.xml.wrapper.Element
	{
		public LinePriceInfo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEPRICEINFO; }
	}

	public class KitLines extends com.haht.xml.wrapper.Element
	{
		public KitLines(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITLINES; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Enumeration<?> getKitLineList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class Schedules extends com.haht.xml.wrapper.Element
	{
		public Schedules(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SCHEDULES; }

		public Enumeration<?> getScheduleList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class LineOverallTotals extends com.haht.xml.wrapper.Element
	{
		public LineOverallTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEOVERALLTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineInvoicedTotals extends com.haht.xml.wrapper.Element
	{
		public LineInvoicedTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEINVOICEDTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineRemainingTotals extends com.haht.xml.wrapper.Element
	{
		public LineRemainingTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEREMAININGTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineOverallTotalsInEnterpriseCurrency extends com.haht.xml.wrapper.Element
	{
		public LineOverallTotalsInEnterpriseCurrency(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEOVERALLTOTALSINENTERPRISECURRENCY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineRemainingTotalsInEnterpriseCurrency extends com.haht.xml.wrapper.Element
	{
		public LineRemainingTotalsInEnterpriseCurrency(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEREMAININGTOTALSINENTERPRISECURRENCY; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineCharges extends com.haht.xml.wrapper.Element
	{
		public LineCharges(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINECHARGES; }

		public Enumeration<?> getLineChargeList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class LineTaxes extends com.haht.xml.wrapper.Element
	{
		public LineTaxes(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINETAXES; }

		public Enumeration<?> getLineTaxList() { return getAtomList(0, 0).getAtoms(); }
		public TaxSummary getTaxSummary() { return (TaxSummary) getAtom(0, 1); }
	}

	public class PersonInfo extends com.haht.xml.wrapper.Element
	{
		public PersonInfo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFO; }
	}

	public class TaxSummaryDetail extends com.haht.xml.wrapper.Element
	{
		public TaxSummaryDetail(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_TAXSUMMARYDETAIL; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class CreditCardTransactions extends com.haht.xml.wrapper.Element
	{
		public CreditCardTransactions(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CREDITCARDTRANSACTIONS; }

		public CreditCardTransaction getCreditCardTransaction() { return (CreditCardTransaction) getAtom(0, 0); }
	}

	public class Details extends com.haht.xml.wrapper.Element
	{
		public Details(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_DETAILS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public KitDetails getKitDetails() { return (KitDetails) getAtom(0, 1); }
	}

	public class LanguageDescriptionList extends com.haht.xml.wrapper.Element
	{
		public LanguageDescriptionList(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LANGUAGEDESCRIPTIONLIST; }

		public Enumeration<?> getLanguageDescriptionList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class KitLine extends com.haht.xml.wrapper.Element
	{
		public KitLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITLINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class Schedule extends com.haht.xml.wrapper.Element
	{
		public Schedule(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SCHEDULE; }
	}

	public class LineCharge extends com.haht.xml.wrapper.Element
	{
		public LineCharge(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINECHARGE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class LineTax extends com.haht.xml.wrapper.Element
	{
		public LineTax(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINETAX; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class CreditCardTransaction extends com.haht.xml.wrapper.Element
	{
		public CreditCardTransaction(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CREDITCARDTRANSACTION; }
	}

	public class KitDetails extends com.haht.xml.wrapper.Element
	{
		public KitDetails(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITDETAILS; }

		public KitDetail getKitDetail() { return (KitDetail) getAtom(0, 0); }
	}

	public class LanguageDescription extends com.haht.xml.wrapper.Element
	{
		public LanguageDescription(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LANGUAGEDESCRIPTION; }
	}

	public class KitDetail extends com.haht.xml.wrapper.Element
	{
		public KitDetail(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITDETAIL; }
	}


}
