/**
  * YFSFindInventoryInputDoc.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.yantra.xmlwrapper;

/////////////////////////////////////////////////////////////////////////////
// IMPORTS
/////////////////////////////////////////////////////////////////////////////
import java.io.*;
import java.util.*;
import com.haht.xml.*;

public class YFSFindInventoryInputDoc extends com.haht.xml.wrapper.Doc
{
	protected static final int ID_PROMISE = 0;
	protected static final int ID_YFC_DOC = 1;
	protected static final int ID_SHIPNODES = 2;
	protected static final int ID_SHIPTOADDRESS = 3;
	protected static final int ID_PROMISELINES = 4;
	protected static final int ID_PROMISESERVICELINES = 5;
	protected static final int ID_SERVICEASSOCIATIONS = 6;
	protected static final int ID_SHIPNODE = 7;
	protected static final int ID_PROMISELINE = 8;
	protected static final int ID_PROMISESERVICELINE = 9;
	protected static final int ID_SERVICEASSOCIATION = 10;
	protected static final int ID_TAG = 11;
	protected static final int ID_BUNDLEPARENTLINE = 12;


    protected static com.haht.xml.wrapper.ContentModel[] rModels =
    {
		new com.haht.xml.wrapper.ContentModel("Promise", Promise.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("yfc:doc", Yfc_doc.class,  TYPE_TEXT, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ShipNodes", ShipNodes.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ShipToAddress", ShipToAddress.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PromiseLines", PromiseLines.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PromiseServiceLines", PromiseServiceLines.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ServiceAssociations", ServiceAssociations.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ShipNode", ShipNode.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PromiseLine", PromiseLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PromiseServiceLine", PromiseServiceLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ServiceAssociation", ServiceAssociation.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Tag", Tag.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("BundleParentLine", BundleParentLine.class,  TYPE_SEQ, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SHIPNODES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SHIPTOADDRESS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PROMISELINES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PROMISESERVICELINES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SERVICEASSOCIATIONS, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SHIPNODE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PROMISELINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PROMISESERVICELINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SERVICEASSOCIATION, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SHIPNODES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_TAG, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_BUNDLEPARENTLINE, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SHIPNODES, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },

    };

    protected com.haht.xml.wrapper.ContentModel getContentModel(int id)
    {
		return rModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getModelItems(int id)
    {
		return rModelItems[id];
    }

    @SuppressWarnings("rawtypes")
	protected Class getDocumentClass()
    {
		return XercesDoc.class;
    }

    public YFSFindInventoryInputDoc(String xml) throws Exception
    {
		super(xml);
		m_Root = (Promise) getRoot(ID_PROMISE);
    }

    public YFSFindInventoryInputDoc(InputStream xml) throws Exception
    {
		super(xml);
		m_Root = (Promise) getRoot(ID_PROMISE);
    }

    public YFSFindInventoryInputDoc(Reader xml) throws Exception
    {
    	super(xml);
    	m_Root = (Promise) getRoot(ID_PROMISE);
    }

    public Promise getPromise() { return m_Root; }
    Promise m_Root;


    /////////////////////////////////////////////////////////////////////////
    // Element Classes
    /////////////////////////////////////////////////////////////////////////

	public class Promise extends com.haht.xml.wrapper.Element
	{
		public Promise(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PROMISE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public ShipNodes getShipNodes() { return (ShipNodes) getAtom(0, 1); }
		public ShipToAddress getShipToAddress() { return (ShipToAddress) getAtom(0, 2); }
		public PromiseLines getPromiseLines() { return (PromiseLines) getAtom(0, 3); }
		public PromiseServiceLines getPromiseServiceLines() { return (PromiseServiceLines) getAtom(0, 4); }
		public ServiceAssociations getServiceAssociations() { return (ServiceAssociations) getAtom(0, 5); }
	}

	public class Yfc_doc extends com.haht.xml.wrapper.PcdataElement
	{
		public Yfc_doc(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_YFC_DOC; }
	}

	public class ShipNodes extends com.haht.xml.wrapper.Element
	{
		public ShipNodes(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SHIPNODES; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	
		@SuppressWarnings("rawtypes")
		public Enumeration getShipNodeList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class ShipToAddress extends com.haht.xml.wrapper.Element
	{
		public ShipToAddress(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SHIPTOADDRESS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class PromiseLines extends com.haht.xml.wrapper.Element
	{
		public PromiseLines(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PROMISELINES; }

		@SuppressWarnings("rawtypes")
		public Enumeration getPromiseLineList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class PromiseServiceLines extends com.haht.xml.wrapper.Element
	{
		public PromiseServiceLines(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PROMISESERVICELINES; }

		@SuppressWarnings("rawtypes")
		public Enumeration getPromiseServiceLineList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ServiceAssociations extends com.haht.xml.wrapper.Element
	{
		public ServiceAssociations(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SERVICEASSOCIATIONS; }

		public ServiceAssociation getServiceAssociation() { return (ServiceAssociation) getAtom(0, 0); }
	}

	public class ShipNode extends com.haht.xml.wrapper.Element
	{
		public ShipNode(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SHIPNODE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class PromiseLine extends com.haht.xml.wrapper.Element
	{
		public PromiseLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PROMISELINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public ShipNodes getShipNodes() { return (ShipNodes) getAtom(0, 1); }
		public Tag getTag() { return (Tag) getAtom(0, 2); }
		public BundleParentLine getBundleParentLine() { return (BundleParentLine) getAtom(0, 3); }
	}

	public class PromiseServiceLine extends com.haht.xml.wrapper.Element
	{
		public PromiseServiceLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PROMISESERVICELINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public ShipNodes getShipNodes() { return (ShipNodes) getAtom(0, 1); }
	}

	public class ServiceAssociation extends com.haht.xml.wrapper.Element
	{
		public ServiceAssociation(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SERVICEASSOCIATION; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class Tag extends com.haht.xml.wrapper.Element
	{
		public Tag(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_TAG; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class BundleParentLine extends com.haht.xml.wrapper.Element
	{
		public BundleParentLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_BUNDLEPARENTLINE; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}


}
