/**
  * YFSOrderLineDetailsOutputDoc.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.yantra.xmlwrapper;

/////////////////////////////////////////////////////////////////////////////
// IMPORTS
/////////////////////////////////////////////////////////////////////////////
import java.io.*;
import java.util.*;
import com.haht.xml.*;

public class YFSOrderLineDetailsOutputDoc extends com.haht.xml.wrapper.Doc
{
	protected static final int ID_ORDERLINE = 0;
	protected static final int ID_ITEM = 1;
	protected static final int ID_LINEPRICEINFO = 2;
	protected static final int ID_ORDERLINEOPTIONS = 3;
	protected static final int ID_ORDER = 4;
	protected static final int ID_WORKORDERS = 5;
	protected static final int ID_PERSONINFOMARKFOR = 6;
	protected static final int ID_INSTRUCTIONS = 7;
	protected static final int ID_REFERENCES = 8;
	protected static final int ID_KITLINES = 9;
	protected static final int ID_ADDITIONALADDRESSES = 10;
	protected static final int ID_PRODUCTITEMS = 11;
	protected static final int ID_SERVICEASSOCIATIONS = 12;
	protected static final int ID_PRODUCTASSOCIATIONS = 13;
	protected static final int ID_DELIVERYASSOCIATIONS = 14;
	protected static final int ID_PERSONINFOSHIPTO = 15;
	protected static final int ID_SCHEDULES = 16;
	protected static final int ID_LINEOVERALLTOTALS = 17;
	protected static final int ID_LINEINVOICEDTOTALS = 18;
	protected static final int ID_LINEREMAININGTOTALS = 19;
	protected static final int ID_LINECHARGES = 20;
	protected static final int ID_LINETAXES = 21;
	protected static final int ID_ORDERSTATUSES = 22;
	protected static final int ID_ALLOWEDMODIFICATIONS = 23;
	protected static final int ID_CAPACITYALLOCATIONS = 24;
	protected static final int ID_ORDERLINEINVATTREQUEST = 25;
	protected static final int ID_ORDERLINEOPTION = 26;
	protected static final int ID_WORKORDER = 27;
	protected static final int ID_INSTRUCTION = 28;
	protected static final int ID_REFERENCE = 29;
	protected static final int ID_KITLINE = 30;
	protected static final int ID_ADDITIONALADDRESS = 31;
	protected static final int ID_PRODUCTITEM = 32;
	protected static final int ID_SERVICEASSOCIATION = 33;
	protected static final int ID_PRODUCTASSOCIATION = 34;
	protected static final int ID_DELIVERYASSOCIATION = 35;
	protected static final int ID_SCHEDULE = 36;
	protected static final int ID_LINECHARGE = 37;
	protected static final int ID_LINETAX = 38;
	protected static final int ID_TAXSUMMARY = 39;
	protected static final int ID_ORDERSTATUS = 40;
	protected static final int ID_MODIFICATION = 41;
	protected static final int ID_CAPACITYALLOCATION = 42;
	protected static final int ID_PERSONINFO = 43;
	protected static final int ID_PRODUCTLINE = 44;
	protected static final int ID_SERVICELINE = 45;
	protected static final int ID_TAXSUMMARYDETAIL = 46;


    protected static com.haht.xml.wrapper.ContentModel[] rModels =
    {
		new com.haht.xml.wrapper.ContentModel("OrderLine", OrderLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Item", Item.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LinePriceInfo", LinePriceInfo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineOptions", OrderLineOptions.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Order", Order.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("WorkOrders", WorkOrders.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoMarkFor", PersonInfoMarkFor.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Instructions", Instructions.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("References", References.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLines", KitLines.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AdditionalAddresses", AdditionalAddresses.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductItems", ProductItems.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ServiceAssociations", ServiceAssociations.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductAssociations", ProductAssociations.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("DeliveryAssociations", DeliveryAssociations.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfoShipTo", PersonInfoShipTo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Schedules", Schedules.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineOverallTotals", LineOverallTotals.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineInvoicedTotals", LineInvoicedTotals.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineRemainingTotals", LineRemainingTotals.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineCharges", LineCharges.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineTaxes", LineTaxes.class,  TYPE_SEQ, QUAL_STAR),
		new com.haht.xml.wrapper.ContentModel("OrderStatuses", OrderStatuses.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AllowedModifications", AllowedModifications.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("CapacityAllocations", CapacityAllocations.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineInvAttRequest", OrderLineInvAttRequest.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLineOption", OrderLineOption.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("WorkOrder", WorkOrder.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Instruction", Instruction.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Reference", Reference.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("KitLine", KitLine.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("AdditionalAddress", AdditionalAddress.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductItem", ProductItem.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ServiceAssociation", ServiceAssociation.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductAssociation", ProductAssociation.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("DeliveryAssociation", DeliveryAssociation.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Schedule", Schedule.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineCharge", LineCharge.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("LineTax", LineTax.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("TaxSummary", TaxSummary.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderStatus", OrderStatus.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Modification", Modification.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("CapacityAllocation", CapacityAllocation.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PersonInfo", PersonInfo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ProductLine", ProductLine.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ServiceLine", ServiceLine.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("TaxSummaryDetail", TaxSummaryDetail.class,  TYPE_EMPTY, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_ITEM, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEPRICEINFO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINEOPTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDER, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_WORKORDERS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOMARKFOR, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REFERENCES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_KITLINES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTITEMS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SERVICEASSOCIATIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRODUCTASSOCIATIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_DELIVERYASSOCIATIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PERSONINFOSHIPTO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_SCHEDULES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEOVERALLTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEINVOICEDTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINEREMAININGTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINECHARGES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_LINETAXES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERSTATUSES, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ALLOWEDMODIFICATIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_CAPACITYALLOCATIONS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDERLINEINVATTREQUEST, QUAL_HOOK) },
		{ null },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERLINEOPTION, QUAL_STAR) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_WORKORDER, QUAL_STAR) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_INSTRUCTION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_REFERENCE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_KITLINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ADDITIONALADDRESS, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PRODUCTITEM, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_SERVICEASSOCIATION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PRODUCTASSOCIATION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_DELIVERYASSOCIATION, QUAL_STAR) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_SCHEDULE, QUAL_STAR) },
		{ null },
		{ null },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_LINECHARGE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_LINETAX, QUAL_NONE), new com.haht.xml.wrapper.ModelItem(ID_TAXSUMMARY, QUAL_NONE) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERSTATUS, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_MODIFICATION, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_CAPACITYALLOCATION, QUAL_STAR) },
		{ null },
		{ null },
		{ null },
		{ null },
		{ null },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_PERSONINFO, QUAL_NONE) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_PRODUCTLINE, QUAL_NONE), new com.haht.xml.wrapper.ModelItem(ID_SERVICELINE, QUAL_NONE) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PRODUCTLINE, QUAL_NONE), new com.haht.xml.wrapper.ModelItem(ID_SERVICELINE, QUAL_NONE) },
		{ new com.haht.xml.wrapper.ModelItem(ID_PRODUCTLINE, QUAL_NONE), new com.haht.xml.wrapper.ModelItem(ID_SERVICELINE, QUAL_NONE) },
		{ null },
		{ null },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_TAXSUMMARYDETAIL, QUAL_NONE) },
		{ null },
		{ null },
		{ null },
		{ null },
		{ null },
		{ null },
		{ null },

    };

    protected com.haht.xml.wrapper.ContentModel getContentModel(int id)
    {
		return rModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getModelItems(int id)
    {
		return rModelItems[id];
    }

    protected Class<XercesDoc> getDocumentClass()
    {
		return XercesDoc.class;
    }

    public YFSOrderLineDetailsOutputDoc(String xml) throws Exception
    {
		super(xml);
		m_Root = (OrderLine) getRoot(ID_ORDERLINE);
    }

    public YFSOrderLineDetailsOutputDoc(InputStream xml) throws Exception
    {
		super(xml);
		m_Root = (OrderLine) getRoot(ID_ORDERLINE);
    }

    public YFSOrderLineDetailsOutputDoc(Reader xml) throws Exception
    {
    	super(xml);
    	m_Root = (OrderLine) getRoot(ID_ORDERLINE);
    }

    public OrderLine getOrderLine() { return m_Root; }
    OrderLine m_Root;


    /////////////////////////////////////////////////////////////////////////
    // Element Classes
    /////////////////////////////////////////////////////////////////////////

	public class OrderLine extends com.haht.xml.wrapper.Element
	{
		public OrderLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINE; }

		public Item getItem() { return (Item) getAtom(0, 0); }
		public LinePriceInfo getLinePriceInfo() { return (LinePriceInfo) getAtom(0, 1); }
		public OrderLineOptions getOrderLineOptions() { return (OrderLineOptions) getAtom(0, 2); }
		public Order getOrder() { return (Order) getAtom(0, 3); }
		public WorkOrders getWorkOrders() { return (WorkOrders) getAtom(0, 4); }
		public PersonInfoMarkFor getPersonInfoMarkFor() { return (PersonInfoMarkFor) getAtom(0, 5); }
		public Instructions getInstructions() { return (Instructions) getAtom(0, 6); }
		public References getReferences() { return (References) getAtom(0, 7); }
		public KitLines getKitLines() { return (KitLines) getAtom(0, 8); }
		public AdditionalAddresses getAdditionalAddresses() { return (AdditionalAddresses) getAtom(0, 9); }
		public ProductItems getProductItems() { return (ProductItems) getAtom(0, 10); }
		public ServiceAssociations getServiceAssociations() { return (ServiceAssociations) getAtom(0, 11); }
		public ProductAssociations getProductAssociations() { return (ProductAssociations) getAtom(0, 12); }
		public DeliveryAssociations getDeliveryAssociations() { return (DeliveryAssociations) getAtom(0, 13); }
		public PersonInfoShipTo getPersonInfoShipTo() { return (PersonInfoShipTo) getAtom(0, 14); }
		public Schedules getSchedules() { return (Schedules) getAtom(0, 15); }
		public LineOverallTotals getLineOverallTotals() { return (LineOverallTotals) getAtom(0, 16); }
		public LineInvoicedTotals getLineInvoicedTotals() { return (LineInvoicedTotals) getAtom(0, 17); }
		public LineRemainingTotals getLineRemainingTotals() { return (LineRemainingTotals) getAtom(0, 18); }
		public LineCharges getLineCharges() { return (LineCharges) getAtom(0, 19); }
		public LineTaxes getLineTaxes() { return (LineTaxes) getAtom(0, 20); }
		public OrderStatuses getOrderStatuses() { return (OrderStatuses) getAtom(0, 21); }
		public AllowedModifications getAllowedModifications() { return (AllowedModifications) getAtom(0, 22); }
		public CapacityAllocations getCapacityAllocations() { return (CapacityAllocations) getAtom(0, 23); }
		public OrderLineInvAttRequest getOrderLineInvAttRequest() { return (OrderLineInvAttRequest) getAtom(0, 24); }
	}

	public class Item extends com.haht.xml.wrapper.Element
	{
		public Item(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ITEM; }
	}

	public class LinePriceInfo extends com.haht.xml.wrapper.Element
	{
		public LinePriceInfo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEPRICEINFO; }
	}

	public class OrderLineOptions extends com.haht.xml.wrapper.Element
	{
		public OrderLineOptions(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINEOPTIONS; }

		public Enumeration<?> getOrderLineOptionList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class Order extends com.haht.xml.wrapper.Element
	{
		public Order(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDER; }
	}

	public class WorkOrders extends com.haht.xml.wrapper.Element
	{
		public WorkOrders(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_WORKORDERS; }

		public Enumeration<?> getWorkOrderList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class PersonInfoMarkFor extends com.haht.xml.wrapper.Element
	{
		public PersonInfoMarkFor(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOMARKFOR; }
	}

	public class Instructions extends com.haht.xml.wrapper.Element
	{
		public Instructions(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INSTRUCTIONS; }

		public Enumeration<?> getInstructionList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class References extends com.haht.xml.wrapper.Element
	{
		public References(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REFERENCES; }

		public Enumeration<?> getReferenceList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class KitLines extends com.haht.xml.wrapper.Element
	{
		public KitLines(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITLINES; }

		public Enumeration<?> getKitLineList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class AdditionalAddresses extends com.haht.xml.wrapper.Element
	{
		public AdditionalAddresses(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ADDITIONALADDRESSES; }

		public Enumeration<?> getAdditionalAddressList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ProductItems extends com.haht.xml.wrapper.Element
	{
		public ProductItems(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTITEMS; }

		public Enumeration<?> getProductItemList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ServiceAssociations extends com.haht.xml.wrapper.Element
	{
		public ServiceAssociations(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SERVICEASSOCIATIONS; }

		public Enumeration<?> getServiceAssociationList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ProductAssociations extends com.haht.xml.wrapper.Element
	{
		public ProductAssociations(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTASSOCIATIONS; }

		public Enumeration<?> getProductAssociationList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class DeliveryAssociations extends com.haht.xml.wrapper.Element
	{
		public DeliveryAssociations(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_DELIVERYASSOCIATIONS; }

		public Enumeration<?> getDeliveryAssociationList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class PersonInfoShipTo extends com.haht.xml.wrapper.Element
	{
		public PersonInfoShipTo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFOSHIPTO; }
	}

	public class Schedules extends com.haht.xml.wrapper.Element
	{
		public Schedules(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SCHEDULES; }

		public Enumeration<?> getScheduleList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class LineOverallTotals extends com.haht.xml.wrapper.Element
	{
		public LineOverallTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEOVERALLTOTALS; }
	}

	public class LineInvoicedTotals extends com.haht.xml.wrapper.Element
	{
		public LineInvoicedTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEINVOICEDTOTALS; }
	}

	public class LineRemainingTotals extends com.haht.xml.wrapper.Element
	{
		public LineRemainingTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINEREMAININGTOTALS; }
	}

	public class LineCharges extends com.haht.xml.wrapper.Element
	{
		public LineCharges(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINECHARGES; }

		public Enumeration<?> getLineChargeList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class LineTaxes extends com.haht.xml.wrapper.Element
	{
		public LineTaxes(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINETAXES; }

		public int getUnitCount() { return getContentUnitCount(); }
		public LineTax getLineTax(int i) { return (LineTax) getAtom(i, 0); }
		public TaxSummary getTaxSummary(int i) { return (TaxSummary) getAtom(i, 1); }
	}

	public class OrderStatuses extends com.haht.xml.wrapper.Element
	{
		public OrderStatuses(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERSTATUSES; }

		public Enumeration<?> getOrderStatusList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class AllowedModifications extends com.haht.xml.wrapper.Element
	{
		public AllowedModifications(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ALLOWEDMODIFICATIONS; }

		public Enumeration<?> getModificationList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class CapacityAllocations extends com.haht.xml.wrapper.Element
	{
		public CapacityAllocations(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CAPACITYALLOCATIONS; }

		public Enumeration<?> getCapacityAllocationList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class OrderLineInvAttRequest extends com.haht.xml.wrapper.Element
	{
		public OrderLineInvAttRequest(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINEINVATTREQUEST; }
	}

	public class OrderLineOption extends com.haht.xml.wrapper.Element
	{
		public OrderLineOption(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINEOPTION; }
	}

	public class WorkOrder extends com.haht.xml.wrapper.Element
	{
		public WorkOrder(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_WORKORDER; }
	}

	public class Instruction extends com.haht.xml.wrapper.Element
	{
		public Instruction(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INSTRUCTION; }
	}

	public class Reference extends com.haht.xml.wrapper.Element
	{
		public Reference(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REFERENCE; }
	}

	public class KitLine extends com.haht.xml.wrapper.Element
	{
		public KitLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_KITLINE; }
	}

	public class AdditionalAddress extends com.haht.xml.wrapper.Element
	{
		public AdditionalAddress(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ADDITIONALADDRESS; }

		public PersonInfo getPersonInfo() { return (PersonInfo) getAtom(0, 0); }
	}

	public class ProductItem extends com.haht.xml.wrapper.Element
	{
		public ProductItem(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTITEM; }
	}

	public class ServiceAssociation extends com.haht.xml.wrapper.Element
	{
		public ServiceAssociation(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SERVICEASSOCIATION; }

		public ProductLine getProductLine() { return (ProductLine) getAtom(0, 0); }
		public ServiceLine getServiceLine() { return (ServiceLine) getAtom(0, 1); }
	}

	public class ProductAssociation extends com.haht.xml.wrapper.Element
	{
		public ProductAssociation(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTASSOCIATION; }

		public ProductLine getProductLine() { return (ProductLine) getAtom(0, 0); }
		public ServiceLine getServiceLine() { return (ServiceLine) getAtom(0, 1); }
	}

	public class DeliveryAssociation extends com.haht.xml.wrapper.Element
	{
		public DeliveryAssociation(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_DELIVERYASSOCIATION; }

		public ProductLine getProductLine() { return (ProductLine) getAtom(0, 0); }
		public ServiceLine getServiceLine() { return (ServiceLine) getAtom(0, 1); }
	}

	public class Schedule extends com.haht.xml.wrapper.Element
	{
		public Schedule(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SCHEDULE; }
	}

	public class LineCharge extends com.haht.xml.wrapper.Element
	{
		public LineCharge(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINECHARGE; }
	}

	public class LineTax extends com.haht.xml.wrapper.Element
	{
		public LineTax(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_LINETAX; }
	}

	public class TaxSummary extends com.haht.xml.wrapper.Element
	{
		public TaxSummary(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_TAXSUMMARY; }

		public TaxSummaryDetail getTaxSummaryDetail() { return (TaxSummaryDetail) getAtom(0, 0); }
	}

	public class OrderStatus extends com.haht.xml.wrapper.Element
	{
		public OrderStatus(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERSTATUS; }
	}

	public class Modification extends com.haht.xml.wrapper.Element
	{
		public Modification(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_MODIFICATION; }
	}

	public class CapacityAllocation extends com.haht.xml.wrapper.Element
	{
		public CapacityAllocation(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_CAPACITYALLOCATION; }
	}

	public class PersonInfo extends com.haht.xml.wrapper.Element
	{
		public PersonInfo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PERSONINFO; }
	}

	public class ProductLine extends com.haht.xml.wrapper.Element
	{
		public ProductLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRODUCTLINE; }
	}

	public class ServiceLine extends com.haht.xml.wrapper.Element
	{
		public ServiceLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_SERVICELINE; }
	}

	public class TaxSummaryDetail extends com.haht.xml.wrapper.Element
	{
		public TaxSummaryDetail(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_TAXSUMMARYDETAIL; }
	}


}
