/**
  * YFSOrderListOutputDoc.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.yantra.xmlwrapper;

/////////////////////////////////////////////////////////////////////////////
// IMPORTS
/////////////////////////////////////////////////////////////////////////////
import java.io.*;
import java.util.*;
import com.haht.xml.*;

public class YFSOrderListOutputDoc extends com.haht.xml.wrapper.Doc
{
	protected static final int ID_ORDERLIST = 0;
	protected static final int ID_YFC_DOC = 1;
	protected static final int ID_ORDER = 2;
	protected static final int ID_PRICEINFO = 3;
	protected static final int ID_OVERALLTOTALS = 4;
	protected static final int ID_INVOICEDTOTALS = 5;
	protected static final int ID_REMAININGTOTALS = 6;


    protected static com.haht.xml.wrapper.ContentModel[] rModels =
    {
		new com.haht.xml.wrapper.ContentModel("OrderList", OrderList.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("yfc:doc", Yfc_doc.class,  TYPE_TEXT, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Order", Order.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("PriceInfo", PriceInfo.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OverallTotals", OverallTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("InvoicedTotals", InvoicedTotals.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("RemainingTotals", RemainingTotals.class,  TYPE_SEQ, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_ORDER, QUAL_STAR) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_PRICEINFO, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_OVERALLTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_INVOICEDTOTALS, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_REMAININGTOTALS, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },

    };

    protected com.haht.xml.wrapper.ContentModel getContentModel(int id)
    {
		return rModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getModelItems(int id)
    {
		return rModelItems[id];
    }

    @SuppressWarnings("rawtypes")
	protected Class getDocumentClass()
    {
		return XercesDoc.class;
    }

    public YFSOrderListOutputDoc(String xml) throws Exception
    {
		super(xml);
		m_Root = (OrderList) getRoot(ID_ORDERLIST);
    }

    public YFSOrderListOutputDoc(InputStream xml) throws Exception
    {
		super(xml);
		m_Root = (OrderList) getRoot(ID_ORDERLIST);
    }

    public YFSOrderListOutputDoc(Reader xml) throws Exception
    {
    	super(xml);
    	m_Root = (OrderList) getRoot(ID_ORDERLIST);
    }

    public OrderList getOrderList() { return m_Root; }
    OrderList m_Root;


    /////////////////////////////////////////////////////////////////////////
    // Element Classes
    /////////////////////////////////////////////////////////////////////////

	public class OrderList extends com.haht.xml.wrapper.Element
	{
		public OrderList(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLIST; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		@SuppressWarnings("rawtypes")
		public Enumeration getOrderList() { return getAtomList(0, 1).getAtoms(); }
	}

	public class Yfc_doc extends com.haht.xml.wrapper.PcdataElement
	{
		public Yfc_doc(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_YFC_DOC; }
	}

	public class Order extends com.haht.xml.wrapper.Element
	{
		public Order(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDER; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public PriceInfo getPriceInfo() { return (PriceInfo) getAtom(0, 1); }
		public OverallTotals getOverallTotals() { return (OverallTotals) getAtom(0, 2); }
		public InvoicedTotals getInvoicedTotals() { return (InvoicedTotals) getAtom(0, 3); }
		public RemainingTotals getRemainingTotals() { return (RemainingTotals) getAtom(0, 4); }
	}

	public class PriceInfo extends com.haht.xml.wrapper.Element
	{
		public PriceInfo(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRICEINFO; }
	}

	public class OverallTotals extends com.haht.xml.wrapper.Element
	{
		public OverallTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_OVERALLTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class InvoicedTotals extends com.haht.xml.wrapper.Element
	{
		public InvoicedTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_INVOICEDTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}

	public class RemainingTotals extends com.haht.xml.wrapper.Element
	{
		public RemainingTotals(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_REMAININGTOTALS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}


}
