/**
  * YFSPriceSetDetailsOutputDoc.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.yantra.xmlwrapper;

/////////////////////////////////////////////////////////////////////////////
// IMPORTS
/////////////////////////////////////////////////////////////////////////////
import java.io.*;
import java.util.*;
import com.haht.xml.*;

public class YFSPriceSetDetailsOutputDoc extends com.haht.xml.wrapper.Doc
{
	protected static final int ID_PRICESET = 0;
	protected static final int ID_ITEMPRICESETLIST = 1;
	protected static final int ID_ITEMPRICESET = 2;
	protected static final int ID_ITEMPRICESETDTLLIST = 3;
	protected static final int ID_ITEMPRICESETDTL = 4;


    protected static com.haht.xml.wrapper.ContentModel[] rModels =
    {
		new com.haht.xml.wrapper.ContentModel("PriceSet", PriceSet.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ItemPriceSetList", ItemPriceSetList.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ItemPriceSet", ItemPriceSet.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ItemPriceSetDtlList", ItemPriceSetDtlList.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("ItemPriceSetDtl", ItemPriceSetDtl.class,  TYPE_EMPTY, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_ITEMPRICESETLIST, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ITEMPRICESET, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ITEMPRICESETDTLLIST, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ITEMPRICESETDTL, QUAL_STAR) },
		{ null },

    };

    protected com.haht.xml.wrapper.ContentModel getContentModel(int id)
    {
		return rModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getModelItems(int id)
    {
		return rModelItems[id];
    }

    @SuppressWarnings("rawtypes")
	protected Class getDocumentClass()
    {
		return XercesDoc.class;
    }

    public YFSPriceSetDetailsOutputDoc(String xml) throws Exception
    {
		super(xml);
		m_Root = (PriceSet) getRoot(ID_PRICESET);
    }

    public YFSPriceSetDetailsOutputDoc(InputStream xml) throws Exception
    {
		super(xml);
		m_Root = (PriceSet) getRoot(ID_PRICESET);
    }

    public YFSPriceSetDetailsOutputDoc(Reader xml) throws Exception
    {
    	super(xml);
    	m_Root = (PriceSet) getRoot(ID_PRICESET);
    }

    public PriceSet getPriceSet() { return m_Root; }
    PriceSet m_Root;


    /////////////////////////////////////////////////////////////////////////
    // Element Classes
    /////////////////////////////////////////////////////////////////////////

	public class PriceSet extends com.haht.xml.wrapper.Element
	{
		public PriceSet(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_PRICESET; }

		public ItemPriceSetList getItemPriceSetList() { return (ItemPriceSetList) getAtom(0, 0); }
	}

	public class ItemPriceSetList extends com.haht.xml.wrapper.Element
	{
		public ItemPriceSetList(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ITEMPRICESETLIST; }

		@SuppressWarnings("rawtypes")
		public Enumeration getItemPriceSetList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ItemPriceSet extends com.haht.xml.wrapper.Element
	{
		public ItemPriceSet(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ITEMPRICESET; }

		public ItemPriceSetDtlList getItemPriceSetDtlList() { return (ItemPriceSetDtlList) getAtom(0, 0); }
	}

	public class ItemPriceSetDtlList extends com.haht.xml.wrapper.Element
	{
		public ItemPriceSetDtlList(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ITEMPRICESETDTLLIST; }

		@SuppressWarnings("rawtypes")
		public Enumeration getItemPriceSetDtlList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class ItemPriceSetDtl extends com.haht.xml.wrapper.Element
	{
		public ItemPriceSetDtl(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ITEMPRICESETDTL; }
	}


}
