/**
  * YFSScheduleOnBackOrderEventDoc.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.yantra.xmlwrapper;

/////////////////////////////////////////////////////////////////////////////
// IMPORTS
/////////////////////////////////////////////////////////////////////////////
import java.io.*;
import java.util.*;
import com.haht.xml.*;

public class YFSScheduleOnBackOrderEventDoc extends com.haht.xml.wrapper.Doc
{
	protected static final int ID_ORDER = 0;
	protected static final int ID_ORDERLINES = 1;
	protected static final int ID_ORDERLINE = 2;
	protected static final int ID_ITEM = 3;
	protected static final int ID_STATUSBREAKUPFORBACKORDEREDQTY = 4;
	protected static final int ID_BACKORDEREDFROM = 5;
	protected static final int ID_YFC_DOC = 6;
	protected static final int ID_DETAILS = 7;


    protected static com.haht.xml.wrapper.ContentModel[] rModels =
    {
		new com.haht.xml.wrapper.ContentModel("Order", Order.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLines", OrderLines.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("OrderLine", OrderLine.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Item", Item.class,  TYPE_EMPTY, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("StatusBreakupForBackOrderedQty", StatusBreakupForBackOrderedQty.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("BackOrderedFrom", BackOrderedFrom.class,  TYPE_SEQ, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("yfc:doc", Yfc_doc.class,  TYPE_TEXT, QUAL_NONE),
		new com.haht.xml.wrapper.ContentModel("Details", Details.class,  TYPE_SEQ, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rModelItems = 
    {
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERLINES, QUAL_HOOK) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ORDERLINE, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_ITEM, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_STATUSBREAKUPFORBACKORDEREDQTY, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_BACKORDEREDFROM, QUAL_STAR) },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK), new com.haht.xml.wrapper.ModelItem(ID_DETAILS, QUAL_HOOK) },
		{ null },
		{ new com.haht.xml.wrapper.ModelItem(ID_YFC_DOC, QUAL_HOOK) },

    };

    protected com.haht.xml.wrapper.ContentModel getContentModel(int id)
    {
		return rModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getModelItems(int id)
    {
		return rModelItems[id];
    }

    @SuppressWarnings("rawtypes")
	protected Class getDocumentClass()
    {
		return XercesDoc.class;
    }

    public YFSScheduleOnBackOrderEventDoc(String xml) throws Exception
    {
		super(xml);
		m_Root = (Order) getRoot(ID_ORDER);
    }

    public YFSScheduleOnBackOrderEventDoc(InputStream xml) throws Exception
    {
		super(xml);
		m_Root = (Order) getRoot(ID_ORDER);
    }

    public YFSScheduleOnBackOrderEventDoc(Reader xml) throws Exception
    {
    	super(xml);
    	m_Root = (Order) getRoot(ID_ORDER);
    }

    public Order getOrder() { return m_Root; }
    Order m_Root;


    /////////////////////////////////////////////////////////////////////////
    // Element Classes
    /////////////////////////////////////////////////////////////////////////

	public class Order extends com.haht.xml.wrapper.Element
	{
		public Order(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDER; }

		public OrderLines getOrderLines() { return (OrderLines) getAtom(0, 0); }
	}

	public class OrderLines extends com.haht.xml.wrapper.Element
	{
		public OrderLines(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINES; }

		@SuppressWarnings("rawtypes")
		public Enumeration getOrderLineList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class OrderLine extends com.haht.xml.wrapper.Element
	{
		public OrderLine(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ORDERLINE; }

		public Item getItem() { return (Item) getAtom(0, 0); }
		public StatusBreakupForBackOrderedQty getStatusBreakupForBackOrderedQty() { return (StatusBreakupForBackOrderedQty) getAtom(0, 1); }
	}

	public class Item extends com.haht.xml.wrapper.Element
	{
		public Item(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_ITEM; }
	}

	public class StatusBreakupForBackOrderedQty extends com.haht.xml.wrapper.Element
	{
		public StatusBreakupForBackOrderedQty(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_STATUSBREAKUPFORBACKORDEREDQTY; }

		@SuppressWarnings("rawtypes")
		public Enumeration getBackOrderedFromList() { return getAtomList(0, 0).getAtoms(); }
	}

	public class BackOrderedFrom extends com.haht.xml.wrapper.Element
	{
		public BackOrderedFrom(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_BACKORDEREDFROM; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
		public Details getDetails() { return (Details) getAtom(0, 1); }
	}

	public class Yfc_doc extends com.haht.xml.wrapper.PcdataElement
	{
		public Yfc_doc(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_YFC_DOC; }
	}

	public class Details extends com.haht.xml.wrapper.Element
	{
		public Details(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_DETAILS; }

		public Yfc_doc getYfc_doc() { return (Yfc_doc) getAtom(0, 0); }
	}


}
