/**
  * XMLMapperParametersDoc.java
  *
  *	This code was generated by HAHTsite
  *
  **/

/////////////////////////////////////////////////////////////////////////////
// PACKAGE
/////////////////////////////////////////////////////////////////////////////
package com.custom.yantra.xmlmapper;

/////////////////////////////////////////////////////////////////////////////
// IMPORTS
/////////////////////////////////////////////////////////////////////////////
import java.io.*;
import com.haht.xml.*;

public class XMLMapperParametersDoc extends com.haht.xml.wrapper.Doc
{
	protected static final int ID_XMLMAPPERPARAMETERS = 0;


    protected static com.haht.xml.wrapper.ContentModel[] rModels =
    {
		new com.haht.xml.wrapper.ContentModel("XMLMapperParameters", XMLMapperParameters.class,  TYPE_TEXT, QUAL_NONE),

    };

    protected static com.haht.xml.wrapper.ModelItem[][] rModelItems = 
    {
		{ null },

    };

    protected com.haht.xml.wrapper.ContentModel getContentModel(int id)
    {
		return rModels[id];
    }

    protected com.haht.xml.wrapper.ModelItem[] getModelItems(int id)
    {
		return rModelItems[id];
    }

    @SuppressWarnings("rawtypes")
	protected Class getDocumentClass()
    {
		return XercesDoc.class;
    }

    public XMLMapperParametersDoc(String xml) throws Exception
    {
		super(xml);
		m_Root = (XMLMapperParameters) getRoot(ID_XMLMAPPERPARAMETERS);
    }

    public XMLMapperParametersDoc(InputStream xml) throws Exception
    {
		super(xml);
		m_Root = (XMLMapperParameters) getRoot(ID_XMLMAPPERPARAMETERS);
    }

    public XMLMapperParametersDoc(Reader xml) throws Exception
    {
    	super(xml);
    	m_Root = (XMLMapperParameters) getRoot(ID_XMLMAPPERPARAMETERS);
    }

    public XMLMapperParameters getXMLMapperParameters() { return m_Root; }
    XMLMapperParameters m_Root;


    /////////////////////////////////////////////////////////////////////////
    // Element Classes
    /////////////////////////////////////////////////////////////////////////

	public class XMLMapperParameters extends com.haht.xml.wrapper.PcdataElement
	{
		public XMLMapperParameters(com.haht.xml.wrapper.Doc doc, org.w3c.dom.Element elem) { super(doc, elem); }
		public int getID() { return ID_XMLMAPPERPARAMETERS; }
	}


}
